[{"id":170834090,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/170834090","actor":{"login":"pengwynn","id":865,"avatar_url":"https://avatars.githubusercontent.com/u/865?v=2","gravatar_id":"","url":"https://api.github.com/users/pengwynn","html_url":"https://github.com/pengwynn","followers_url":"https://api.github.com/users/pengwynn/followers","following_url":"https://api.github.com/users/pengwynn/following{/other_user}","gists_url":"https://api.github.com/users/pengwynn/gists{/gist_id}","starred_url":"https://api.github.com/users/pengwynn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/pengwynn/subscriptions","organizations_url":"https://api.github.com/users/pengwynn/orgs","repos_url":"https://api.github.com/users/pengwynn/repos","events_url":"https://api.github.com/users/pengwynn/events{/privacy}","received_events_url":"https://api.github.com/users/pengwynn/received_events","type":"User","site_admin":true},"event":"closed","commit_id":null,"created_at":"2014-09-26T17:19:01Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/511","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/511/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/511/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/511/events","html_url":"https://github.com/octokit/octokit.rb/issues/511","id":44085139,"number":511,"title":"Calling @client.authorizations returns Octokit::NotFound  ","user":{"login":"ahmdrefat","id":431262,"avatar_url":"https://avatars.githubusercontent.com/u/431262?v=2","gravatar_id":"","url":"https://api.github.com/users/ahmdrefat","html_url":"https://github.com/ahmdrefat","followers_url":"https://api.github.com/users/ahmdrefat/followers","following_url":"https://api.github.com/users/ahmdrefat/following{/other_user}","gists_url":"https://api.github.com/users/ahmdrefat/gists{/gist_id}","starred_url":"https://api.github.com/users/ahmdrefat/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ahmdrefat/subscriptions","organizations_url":"https://api.github.com/users/ahmdrefat/orgs","repos_url":"https://api.github.com/users/ahmdrefat/repos","events_url":"https://api.github.com/users/ahmdrefat/events{/privacy}","received_events_url":"https://api.github.com/users/ahmdrefat/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"milestone":null,"comments":1,"created_at":"2014-09-26T17:15:39Z","updated_at":"2014-09-26T17:19:01Z","closed_at":"2014-09-26T17:19:01Z","body":"I've create the ```@client``` with the a valid access token, but calling ```authorizations``` always return 404, even if I did the same request with curl or faraday!"}},{"id":169627748,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/169627748","actor":{"login":"AdrienGiboire","id":394860,"avatar_url":"https://avatars.githubusercontent.com/u/394860?v=2","gravatar_id":"","url":"https://api.github.com/users/AdrienGiboire","html_url":"https://github.com/AdrienGiboire","followers_url":"https://api.github.com/users/AdrienGiboire/followers","following_url":"https://api.github.com/users/AdrienGiboire/following{/other_user}","gists_url":"https://api.github.com/users/AdrienGiboire/gists{/gist_id}","starred_url":"https://api.github.com/users/AdrienGiboire/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AdrienGiboire/subscriptions","organizations_url":"https://api.github.com/users/AdrienGiboire/orgs","repos_url":"https://api.github.com/users/AdrienGiboire/repos","events_url":"https://api.github.com/users/AdrienGiboire/events{/privacy}","received_events_url":"https://api.github.com/users/AdrienGiboire/received_events","type":"User","site_admin":false},"event":"subscribed","commit_id":null,"created_at":"2014-09-24T14:35:54Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/510","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/events","html_url":"https://github.com/octokit/octokit.rb/issues/510","id":43755109,"number":510,"title":"Creating a pull request using Octokit fails","user":{"login":"AdrienGiboire","id":394860,"avatar_url":"https://avatars.githubusercontent.com/u/394860?v=2","gravatar_id":"","url":"https://api.github.com/users/AdrienGiboire","html_url":"https://github.com/AdrienGiboire","followers_url":"https://api.github.com/users/AdrienGiboire/followers","following_url":"https://api.github.com/users/AdrienGiboire/following{/other_user}","gists_url":"https://api.github.com/users/AdrienGiboire/gists{/gist_id}","starred_url":"https://api.github.com/users/AdrienGiboire/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AdrienGiboire/subscriptions","organizations_url":"https://api.github.com/users/AdrienGiboire/orgs","repos_url":"https://api.github.com/users/AdrienGiboire/repos","events_url":"https://api.github.com/users/AdrienGiboire/events{/privacy}","received_events_url":"https://api.github.com/users/AdrienGiboire/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"milestone":null,"comments":12,"created_at":"2014-09-24T11:44:53Z","updated_at":"2014-09-24T16:47:40Z","closed_at":null,"body":"I develop the `git-pulls` gem. Sources are available here: https://github.com/schacon/git-pulls/\r\n\r\nThis is to say that everything is working fine. But yesterday, I started working on a new feature. I want to allow user to open/close pull requests using the gem.\r\n\r\nHere is what I currently have:\r\n\r\n```ruby\r\n      def open\r\n        while arg = @args.shift\r\n          case arg\r\n          when '-t'\r\n            title = @args.shift\r\n          when '-m'\r\n            description = @args.shift\r\n          end\r\n        end\r\n    \r\n        head = File.read(File.join(GIT_PATH.call, '/HEAD')).sub!('ref: ', '')\r\n        base = \"refs/remotes/#{GIT_REMOTE}/master\"\r\n    \r\n        url_memo = Hash.new { |h,k| h[k]=[] }\r\n        git('remote -v').to_s.split(\"\\n\").map do |line|\r\n          next if line !~ /^(.+?)\\t(.+) \\(/\r\n          name, url = $1, $2\r\n          url_memo[name] << url\r\n        end\r\n        url = url_memo[GIT_REMOTE].uniq[0]\r\n        if url\r\n          repo = url.scan(/^git@github.com:(.+)\\.git/)[0][0]\r\n    \r\n          Octokit.create_pull_request(repo, base, head, title, description)\r\n        end\r\n      end\r\n```\r\n\r\nFor some reasons, the PR creation doesn't work. I keep getting this error:\r\n\r\n    $ ./bin/git-pulls open -t \"Fake PR\" -m \"Fake PR description\"\r\n\r\n    /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/schacon/git-pulls/pulls: 404 - Not Found // See: https://developer.github.com/v3 (Octokit::NotFound)\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:9:in `block in call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:57:in `on_complete'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:177:in `post'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/sawyer-0.5.5/lib/sawyer/agent.rb:94:in `call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client.rb:339:in `request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client.rb:144:in `post'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client/pull_requests.rb:66:in `create_pull_request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit.rb:27:in `method_missing'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:184:in `open'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:34:in `run'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:21:in `start'\r\n        from ./bin/git-pulls:6:in `<main>'\r\n\r\nYet, https://api.github.com/repos/schacon/git-pulls/pulls exists and according to the [documentation](https://developer.github.com/v3/pulls/#create-a-pull-request) it doesn't seem to be violating any rules.\r\n\r\nCurrently running:\r\n\r\n* Ruby 2.1.2\r\n* Octokit 3.3.1\r\n\r\nParameters sent to the `Octokit#create_pull_request` in this example are:\r\n\r\n* `repo` equals `schacon/git-pulls`\r\n* `base` equals `refs/remotes/origin/master`\r\n* `head` equals `refs/heads/feature/open_close_commands`\r\n* `title` equals `Fake PR`\r\n* `description` equals `Fake PR description`\r\n\r\nAny hints?"}},{"id":169627747,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/169627747","actor":{"login":"AdrienGiboire","id":394860,"avatar_url":"https://avatars.githubusercontent.com/u/394860?v=2","gravatar_id":"","url":"https://api.github.com/users/AdrienGiboire","html_url":"https://github.com/AdrienGiboire","followers_url":"https://api.github.com/users/AdrienGiboire/followers","following_url":"https://api.github.com/users/AdrienGiboire/following{/other_user}","gists_url":"https://api.github.com/users/AdrienGiboire/gists{/gist_id}","starred_url":"https://api.github.com/users/AdrienGiboire/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AdrienGiboire/subscriptions","organizations_url":"https://api.github.com/users/AdrienGiboire/orgs","repos_url":"https://api.github.com/users/AdrienGiboire/repos","events_url":"https://api.github.com/users/AdrienGiboire/events{/privacy}","received_events_url":"https://api.github.com/users/AdrienGiboire/received_events","type":"User","site_admin":false},"event":"mentioned","commit_id":null,"created_at":"2014-09-24T14:35:54Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/510","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/events","html_url":"https://github.com/octokit/octokit.rb/issues/510","id":43755109,"number":510,"title":"Creating a pull request using Octokit fails","user":{"login":"AdrienGiboire","id":394860,"avatar_url":"https://avatars.githubusercontent.com/u/394860?v=2","gravatar_id":"","url":"https://api.github.com/users/AdrienGiboire","html_url":"https://github.com/AdrienGiboire","followers_url":"https://api.github.com/users/AdrienGiboire/followers","following_url":"https://api.github.com/users/AdrienGiboire/following{/other_user}","gists_url":"https://api.github.com/users/AdrienGiboire/gists{/gist_id}","starred_url":"https://api.github.com/users/AdrienGiboire/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AdrienGiboire/subscriptions","organizations_url":"https://api.github.com/users/AdrienGiboire/orgs","repos_url":"https://api.github.com/users/AdrienGiboire/repos","events_url":"https://api.github.com/users/AdrienGiboire/events{/privacy}","received_events_url":"https://api.github.com/users/AdrienGiboire/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"milestone":null,"comments":12,"created_at":"2014-09-24T11:44:53Z","updated_at":"2014-09-24T16:47:40Z","closed_at":null,"body":"I develop the `git-pulls` gem. Sources are available here: https://github.com/schacon/git-pulls/\r\n\r\nThis is to say that everything is working fine. But yesterday, I started working on a new feature. I want to allow user to open/close pull requests using the gem.\r\n\r\nHere is what I currently have:\r\n\r\n```ruby\r\n      def open\r\n        while arg = @args.shift\r\n          case arg\r\n          when '-t'\r\n            title = @args.shift\r\n          when '-m'\r\n            description = @args.shift\r\n          end\r\n        end\r\n    \r\n        head = File.read(File.join(GIT_PATH.call, '/HEAD')).sub!('ref: ', '')\r\n        base = \"refs/remotes/#{GIT_REMOTE}/master\"\r\n    \r\n        url_memo = Hash.new { |h,k| h[k]=[] }\r\n        git('remote -v').to_s.split(\"\\n\").map do |line|\r\n          next if line !~ /^(.+?)\\t(.+) \\(/\r\n          name, url = $1, $2\r\n          url_memo[name] << url\r\n        end\r\n        url = url_memo[GIT_REMOTE].uniq[0]\r\n        if url\r\n          repo = url.scan(/^git@github.com:(.+)\\.git/)[0][0]\r\n    \r\n          Octokit.create_pull_request(repo, base, head, title, description)\r\n        end\r\n      end\r\n```\r\n\r\nFor some reasons, the PR creation doesn't work. I keep getting this error:\r\n\r\n    $ ./bin/git-pulls open -t \"Fake PR\" -m \"Fake PR description\"\r\n\r\n    /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/schacon/git-pulls/pulls: 404 - Not Found // See: https://developer.github.com/v3 (Octokit::NotFound)\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:9:in `block in call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:57:in `on_complete'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:177:in `post'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/sawyer-0.5.5/lib/sawyer/agent.rb:94:in `call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client.rb:339:in `request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client.rb:144:in `post'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client/pull_requests.rb:66:in `create_pull_request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit.rb:27:in `method_missing'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:184:in `open'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:34:in `run'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:21:in `start'\r\n        from ./bin/git-pulls:6:in `<main>'\r\n\r\nYet, https://api.github.com/repos/schacon/git-pulls/pulls exists and according to the [documentation](https://developer.github.com/v3/pulls/#create-a-pull-request) it doesn't seem to be violating any rules.\r\n\r\nCurrently running:\r\n\r\n* Ruby 2.1.2\r\n* Octokit 3.3.1\r\n\r\nParameters sent to the `Octokit#create_pull_request` in this example are:\r\n\r\n* `repo` equals `schacon/git-pulls`\r\n* `base` equals `refs/remotes/origin/master`\r\n* `head` equals `refs/heads/feature/open_close_commands`\r\n* `title` equals `Fake PR`\r\n* `description` equals `Fake PR description`\r\n\r\nAny hints?"}},{"id":169606125,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/169606125","actor":{"login":"pengwynn","id":865,"avatar_url":"https://avatars.githubusercontent.com/u/865?v=2","gravatar_id":"","url":"https://api.github.com/users/pengwynn","html_url":"https://github.com/pengwynn","followers_url":"https://api.github.com/users/pengwynn/followers","following_url":"https://api.github.com/users/pengwynn/following{/other_user}","gists_url":"https://api.github.com/users/pengwynn/gists{/gist_id}","starred_url":"https://api.github.com/users/pengwynn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/pengwynn/subscriptions","organizations_url":"https://api.github.com/users/pengwynn/orgs","repos_url":"https://api.github.com/users/pengwynn/repos","events_url":"https://api.github.com/users/pengwynn/events{/privacy}","received_events_url":"https://api.github.com/users/pengwynn/received_events","type":"User","site_admin":true},"event":"subscribed","commit_id":null,"created_at":"2014-09-24T14:00:34Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/510","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/events","html_url":"https://github.com/octokit/octokit.rb/issues/510","id":43755109,"number":510,"title":"Creating a pull request using Octokit fails","user":{"login":"AdrienGiboire","id":394860,"avatar_url":"https://avatars.githubusercontent.com/u/394860?v=2","gravatar_id":"","url":"https://api.github.com/users/AdrienGiboire","html_url":"https://github.com/AdrienGiboire","followers_url":"https://api.github.com/users/AdrienGiboire/followers","following_url":"https://api.github.com/users/AdrienGiboire/following{/other_user}","gists_url":"https://api.github.com/users/AdrienGiboire/gists{/gist_id}","starred_url":"https://api.github.com/users/AdrienGiboire/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AdrienGiboire/subscriptions","organizations_url":"https://api.github.com/users/AdrienGiboire/orgs","repos_url":"https://api.github.com/users/AdrienGiboire/repos","events_url":"https://api.github.com/users/AdrienGiboire/events{/privacy}","received_events_url":"https://api.github.com/users/AdrienGiboire/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"milestone":null,"comments":12,"created_at":"2014-09-24T11:44:53Z","updated_at":"2014-09-24T16:47:40Z","closed_at":null,"body":"I develop the `git-pulls` gem. Sources are available here: https://github.com/schacon/git-pulls/\r\n\r\nThis is to say that everything is working fine. But yesterday, I started working on a new feature. I want to allow user to open/close pull requests using the gem.\r\n\r\nHere is what I currently have:\r\n\r\n```ruby\r\n      def open\r\n        while arg = @args.shift\r\n          case arg\r\n          when '-t'\r\n            title = @args.shift\r\n          when '-m'\r\n            description = @args.shift\r\n          end\r\n        end\r\n    \r\n        head = File.read(File.join(GIT_PATH.call, '/HEAD')).sub!('ref: ', '')\r\n        base = \"refs/remotes/#{GIT_REMOTE}/master\"\r\n    \r\n        url_memo = Hash.new { |h,k| h[k]=[] }\r\n        git('remote -v').to_s.split(\"\\n\").map do |line|\r\n          next if line !~ /^(.+?)\\t(.+) \\(/\r\n          name, url = $1, $2\r\n          url_memo[name] << url\r\n        end\r\n        url = url_memo[GIT_REMOTE].uniq[0]\r\n        if url\r\n          repo = url.scan(/^git@github.com:(.+)\\.git/)[0][0]\r\n    \r\n          Octokit.create_pull_request(repo, base, head, title, description)\r\n        end\r\n      end\r\n```\r\n\r\nFor some reasons, the PR creation doesn't work. I keep getting this error:\r\n\r\n    $ ./bin/git-pulls open -t \"Fake PR\" -m \"Fake PR description\"\r\n\r\n    /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/schacon/git-pulls/pulls: 404 - Not Found // See: https://developer.github.com/v3 (Octokit::NotFound)\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:9:in `block in call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:57:in `on_complete'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:177:in `post'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/sawyer-0.5.5/lib/sawyer/agent.rb:94:in `call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client.rb:339:in `request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client.rb:144:in `post'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client/pull_requests.rb:66:in `create_pull_request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit.rb:27:in `method_missing'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:184:in `open'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:34:in `run'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:21:in `start'\r\n        from ./bin/git-pulls:6:in `<main>'\r\n\r\nYet, https://api.github.com/repos/schacon/git-pulls/pulls exists and according to the [documentation](https://developer.github.com/v3/pulls/#create-a-pull-request) it doesn't seem to be violating any rules.\r\n\r\nCurrently running:\r\n\r\n* Ruby 2.1.2\r\n* Octokit 3.3.1\r\n\r\nParameters sent to the `Octokit#create_pull_request` in this example are:\r\n\r\n* `repo` equals `schacon/git-pulls`\r\n* `base` equals `refs/remotes/origin/master`\r\n* `head` equals `refs/heads/feature/open_close_commands`\r\n* `title` equals `Fake PR`\r\n* `description` equals `Fake PR description`\r\n\r\nAny hints?"}},{"id":169606124,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/169606124","actor":{"login":"pengwynn","id":865,"avatar_url":"https://avatars.githubusercontent.com/u/865?v=2","gravatar_id":"","url":"https://api.github.com/users/pengwynn","html_url":"https://github.com/pengwynn","followers_url":"https://api.github.com/users/pengwynn/followers","following_url":"https://api.github.com/users/pengwynn/following{/other_user}","gists_url":"https://api.github.com/users/pengwynn/gists{/gist_id}","starred_url":"https://api.github.com/users/pengwynn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/pengwynn/subscriptions","organizations_url":"https://api.github.com/users/pengwynn/orgs","repos_url":"https://api.github.com/users/pengwynn/repos","events_url":"https://api.github.com/users/pengwynn/events{/privacy}","received_events_url":"https://api.github.com/users/pengwynn/received_events","type":"User","site_admin":true},"event":"mentioned","commit_id":null,"created_at":"2014-09-24T14:00:34Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/510","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/events","html_url":"https://github.com/octokit/octokit.rb/issues/510","id":43755109,"number":510,"title":"Creating a pull request using Octokit fails","user":{"login":"AdrienGiboire","id":394860,"avatar_url":"https://avatars.githubusercontent.com/u/394860?v=2","gravatar_id":"","url":"https://api.github.com/users/AdrienGiboire","html_url":"https://github.com/AdrienGiboire","followers_url":"https://api.github.com/users/AdrienGiboire/followers","following_url":"https://api.github.com/users/AdrienGiboire/following{/other_user}","gists_url":"https://api.github.com/users/AdrienGiboire/gists{/gist_id}","starred_url":"https://api.github.com/users/AdrienGiboire/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AdrienGiboire/subscriptions","organizations_url":"https://api.github.com/users/AdrienGiboire/orgs","repos_url":"https://api.github.com/users/AdrienGiboire/repos","events_url":"https://api.github.com/users/AdrienGiboire/events{/privacy}","received_events_url":"https://api.github.com/users/AdrienGiboire/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"milestone":null,"comments":12,"created_at":"2014-09-24T11:44:53Z","updated_at":"2014-09-24T16:47:40Z","closed_at":null,"body":"I develop the `git-pulls` gem. Sources are available here: https://github.com/schacon/git-pulls/\r\n\r\nThis is to say that everything is working fine. But yesterday, I started working on a new feature. I want to allow user to open/close pull requests using the gem.\r\n\r\nHere is what I currently have:\r\n\r\n```ruby\r\n      def open\r\n        while arg = @args.shift\r\n          case arg\r\n          when '-t'\r\n            title = @args.shift\r\n          when '-m'\r\n            description = @args.shift\r\n          end\r\n        end\r\n    \r\n        head = File.read(File.join(GIT_PATH.call, '/HEAD')).sub!('ref: ', '')\r\n        base = \"refs/remotes/#{GIT_REMOTE}/master\"\r\n    \r\n        url_memo = Hash.new { |h,k| h[k]=[] }\r\n        git('remote -v').to_s.split(\"\\n\").map do |line|\r\n          next if line !~ /^(.+?)\\t(.+) \\(/\r\n          name, url = $1, $2\r\n          url_memo[name] << url\r\n        end\r\n        url = url_memo[GIT_REMOTE].uniq[0]\r\n        if url\r\n          repo = url.scan(/^git@github.com:(.+)\\.git/)[0][0]\r\n    \r\n          Octokit.create_pull_request(repo, base, head, title, description)\r\n        end\r\n      end\r\n```\r\n\r\nFor some reasons, the PR creation doesn't work. I keep getting this error:\r\n\r\n    $ ./bin/git-pulls open -t \"Fake PR\" -m \"Fake PR description\"\r\n\r\n    /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/schacon/git-pulls/pulls: 404 - Not Found // See: https://developer.github.com/v3 (Octokit::NotFound)\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:9:in `block in call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:57:in `on_complete'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:177:in `post'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/sawyer-0.5.5/lib/sawyer/agent.rb:94:in `call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client.rb:339:in `request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client.rb:144:in `post'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client/pull_requests.rb:66:in `create_pull_request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit.rb:27:in `method_missing'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:184:in `open'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:34:in `run'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:21:in `start'\r\n        from ./bin/git-pulls:6:in `<main>'\r\n\r\nYet, https://api.github.com/repos/schacon/git-pulls/pulls exists and according to the [documentation](https://developer.github.com/v3/pulls/#create-a-pull-request) it doesn't seem to be violating any rules.\r\n\r\nCurrently running:\r\n\r\n* Ruby 2.1.2\r\n* Octokit 3.3.1\r\n\r\nParameters sent to the `Octokit#create_pull_request` in this example are:\r\n\r\n* `repo` equals `schacon/git-pulls`\r\n* `base` equals `refs/remotes/origin/master`\r\n* `head` equals `refs/heads/feature/open_close_commands`\r\n* `title` equals `Fake PR`\r\n* `description` equals `Fake PR description`\r\n\r\nAny hints?"}},{"id":169602780,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/169602780","actor":{"login":"AdrienGiboire","id":394860,"avatar_url":"https://avatars.githubusercontent.com/u/394860?v=2","gravatar_id":"","url":"https://api.github.com/users/AdrienGiboire","html_url":"https://github.com/AdrienGiboire","followers_url":"https://api.github.com/users/AdrienGiboire/followers","following_url":"https://api.github.com/users/AdrienGiboire/following{/other_user}","gists_url":"https://api.github.com/users/AdrienGiboire/gists{/gist_id}","starred_url":"https://api.github.com/users/AdrienGiboire/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AdrienGiboire/subscriptions","organizations_url":"https://api.github.com/users/AdrienGiboire/orgs","repos_url":"https://api.github.com/users/AdrienGiboire/repos","events_url":"https://api.github.com/users/AdrienGiboire/events{/privacy}","received_events_url":"https://api.github.com/users/AdrienGiboire/received_events","type":"User","site_admin":false},"event":"subscribed","commit_id":null,"created_at":"2014-09-24T13:54:59Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/510","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/events","html_url":"https://github.com/octokit/octokit.rb/issues/510","id":43755109,"number":510,"title":"Creating a pull request using Octokit fails","user":{"login":"AdrienGiboire","id":394860,"avatar_url":"https://avatars.githubusercontent.com/u/394860?v=2","gravatar_id":"","url":"https://api.github.com/users/AdrienGiboire","html_url":"https://github.com/AdrienGiboire","followers_url":"https://api.github.com/users/AdrienGiboire/followers","following_url":"https://api.github.com/users/AdrienGiboire/following{/other_user}","gists_url":"https://api.github.com/users/AdrienGiboire/gists{/gist_id}","starred_url":"https://api.github.com/users/AdrienGiboire/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AdrienGiboire/subscriptions","organizations_url":"https://api.github.com/users/AdrienGiboire/orgs","repos_url":"https://api.github.com/users/AdrienGiboire/repos","events_url":"https://api.github.com/users/AdrienGiboire/events{/privacy}","received_events_url":"https://api.github.com/users/AdrienGiboire/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"milestone":null,"comments":12,"created_at":"2014-09-24T11:44:53Z","updated_at":"2014-09-24T16:47:40Z","closed_at":null,"body":"I develop the `git-pulls` gem. Sources are available here: https://github.com/schacon/git-pulls/\r\n\r\nThis is to say that everything is working fine. But yesterday, I started working on a new feature. I want to allow user to open/close pull requests using the gem.\r\n\r\nHere is what I currently have:\r\n\r\n```ruby\r\n      def open\r\n        while arg = @args.shift\r\n          case arg\r\n          when '-t'\r\n            title = @args.shift\r\n          when '-m'\r\n            description = @args.shift\r\n          end\r\n        end\r\n    \r\n        head = File.read(File.join(GIT_PATH.call, '/HEAD')).sub!('ref: ', '')\r\n        base = \"refs/remotes/#{GIT_REMOTE}/master\"\r\n    \r\n        url_memo = Hash.new { |h,k| h[k]=[] }\r\n        git('remote -v').to_s.split(\"\\n\").map do |line|\r\n          next if line !~ /^(.+?)\\t(.+) \\(/\r\n          name, url = $1, $2\r\n          url_memo[name] << url\r\n        end\r\n        url = url_memo[GIT_REMOTE].uniq[0]\r\n        if url\r\n          repo = url.scan(/^git@github.com:(.+)\\.git/)[0][0]\r\n    \r\n          Octokit.create_pull_request(repo, base, head, title, description)\r\n        end\r\n      end\r\n```\r\n\r\nFor some reasons, the PR creation doesn't work. I keep getting this error:\r\n\r\n    $ ./bin/git-pulls open -t \"Fake PR\" -m \"Fake PR description\"\r\n\r\n    /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/schacon/git-pulls/pulls: 404 - Not Found // See: https://developer.github.com/v3 (Octokit::NotFound)\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:9:in `block in call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:57:in `on_complete'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:177:in `post'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/sawyer-0.5.5/lib/sawyer/agent.rb:94:in `call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client.rb:339:in `request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client.rb:144:in `post'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client/pull_requests.rb:66:in `create_pull_request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit.rb:27:in `method_missing'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:184:in `open'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:34:in `run'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:21:in `start'\r\n        from ./bin/git-pulls:6:in `<main>'\r\n\r\nYet, https://api.github.com/repos/schacon/git-pulls/pulls exists and according to the [documentation](https://developer.github.com/v3/pulls/#create-a-pull-request) it doesn't seem to be violating any rules.\r\n\r\nCurrently running:\r\n\r\n* Ruby 2.1.2\r\n* Octokit 3.3.1\r\n\r\nParameters sent to the `Octokit#create_pull_request` in this example are:\r\n\r\n* `repo` equals `schacon/git-pulls`\r\n* `base` equals `refs/remotes/origin/master`\r\n* `head` equals `refs/heads/feature/open_close_commands`\r\n* `title` equals `Fake PR`\r\n* `description` equals `Fake PR description`\r\n\r\nAny hints?"}},{"id":169602779,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/169602779","actor":{"login":"AdrienGiboire","id":394860,"avatar_url":"https://avatars.githubusercontent.com/u/394860?v=2","gravatar_id":"","url":"https://api.github.com/users/AdrienGiboire","html_url":"https://github.com/AdrienGiboire","followers_url":"https://api.github.com/users/AdrienGiboire/followers","following_url":"https://api.github.com/users/AdrienGiboire/following{/other_user}","gists_url":"https://api.github.com/users/AdrienGiboire/gists{/gist_id}","starred_url":"https://api.github.com/users/AdrienGiboire/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AdrienGiboire/subscriptions","organizations_url":"https://api.github.com/users/AdrienGiboire/orgs","repos_url":"https://api.github.com/users/AdrienGiboire/repos","events_url":"https://api.github.com/users/AdrienGiboire/events{/privacy}","received_events_url":"https://api.github.com/users/AdrienGiboire/received_events","type":"User","site_admin":false},"event":"mentioned","commit_id":null,"created_at":"2014-09-24T13:54:59Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/510","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/events","html_url":"https://github.com/octokit/octokit.rb/issues/510","id":43755109,"number":510,"title":"Creating a pull request using Octokit fails","user":{"login":"AdrienGiboire","id":394860,"avatar_url":"https://avatars.githubusercontent.com/u/394860?v=2","gravatar_id":"","url":"https://api.github.com/users/AdrienGiboire","html_url":"https://github.com/AdrienGiboire","followers_url":"https://api.github.com/users/AdrienGiboire/followers","following_url":"https://api.github.com/users/AdrienGiboire/following{/other_user}","gists_url":"https://api.github.com/users/AdrienGiboire/gists{/gist_id}","starred_url":"https://api.github.com/users/AdrienGiboire/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AdrienGiboire/subscriptions","organizations_url":"https://api.github.com/users/AdrienGiboire/orgs","repos_url":"https://api.github.com/users/AdrienGiboire/repos","events_url":"https://api.github.com/users/AdrienGiboire/events{/privacy}","received_events_url":"https://api.github.com/users/AdrienGiboire/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"milestone":null,"comments":12,"created_at":"2014-09-24T11:44:53Z","updated_at":"2014-09-24T16:47:40Z","closed_at":null,"body":"I develop the `git-pulls` gem. Sources are available here: https://github.com/schacon/git-pulls/\r\n\r\nThis is to say that everything is working fine. But yesterday, I started working on a new feature. I want to allow user to open/close pull requests using the gem.\r\n\r\nHere is what I currently have:\r\n\r\n```ruby\r\n      def open\r\n        while arg = @args.shift\r\n          case arg\r\n          when '-t'\r\n            title = @args.shift\r\n          when '-m'\r\n            description = @args.shift\r\n          end\r\n        end\r\n    \r\n        head = File.read(File.join(GIT_PATH.call, '/HEAD')).sub!('ref: ', '')\r\n        base = \"refs/remotes/#{GIT_REMOTE}/master\"\r\n    \r\n        url_memo = Hash.new { |h,k| h[k]=[] }\r\n        git('remote -v').to_s.split(\"\\n\").map do |line|\r\n          next if line !~ /^(.+?)\\t(.+) \\(/\r\n          name, url = $1, $2\r\n          url_memo[name] << url\r\n        end\r\n        url = url_memo[GIT_REMOTE].uniq[0]\r\n        if url\r\n          repo = url.scan(/^git@github.com:(.+)\\.git/)[0][0]\r\n    \r\n          Octokit.create_pull_request(repo, base, head, title, description)\r\n        end\r\n      end\r\n```\r\n\r\nFor some reasons, the PR creation doesn't work. I keep getting this error:\r\n\r\n    $ ./bin/git-pulls open -t \"Fake PR\" -m \"Fake PR description\"\r\n\r\n    /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/schacon/git-pulls/pulls: 404 - Not Found // See: https://developer.github.com/v3 (Octokit::NotFound)\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:9:in `block in call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:57:in `on_complete'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:177:in `post'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/sawyer-0.5.5/lib/sawyer/agent.rb:94:in `call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client.rb:339:in `request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client.rb:144:in `post'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client/pull_requests.rb:66:in `create_pull_request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit.rb:27:in `method_missing'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:184:in `open'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:34:in `run'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:21:in `start'\r\n        from ./bin/git-pulls:6:in `<main>'\r\n\r\nYet, https://api.github.com/repos/schacon/git-pulls/pulls exists and according to the [documentation](https://developer.github.com/v3/pulls/#create-a-pull-request) it doesn't seem to be violating any rules.\r\n\r\nCurrently running:\r\n\r\n* Ruby 2.1.2\r\n* Octokit 3.3.1\r\n\r\nParameters sent to the `Octokit#create_pull_request` in this example are:\r\n\r\n* `repo` equals `schacon/git-pulls`\r\n* `base` equals `refs/remotes/origin/master`\r\n* `head` equals `refs/heads/feature/open_close_commands`\r\n* `title` equals `Fake PR`\r\n* `description` equals `Fake PR description`\r\n\r\nAny hints?"}},{"id":169601282,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/169601282","actor":{"login":"AdrienGiboire","id":394860,"avatar_url":"https://avatars.githubusercontent.com/u/394860?v=2","gravatar_id":"","url":"https://api.github.com/users/AdrienGiboire","html_url":"https://github.com/AdrienGiboire","followers_url":"https://api.github.com/users/AdrienGiboire/followers","following_url":"https://api.github.com/users/AdrienGiboire/following{/other_user}","gists_url":"https://api.github.com/users/AdrienGiboire/gists{/gist_id}","starred_url":"https://api.github.com/users/AdrienGiboire/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AdrienGiboire/subscriptions","organizations_url":"https://api.github.com/users/AdrienGiboire/orgs","repos_url":"https://api.github.com/users/AdrienGiboire/repos","events_url":"https://api.github.com/users/AdrienGiboire/events{/privacy}","received_events_url":"https://api.github.com/users/AdrienGiboire/received_events","type":"User","site_admin":false},"event":"subscribed","commit_id":null,"created_at":"2014-09-24T13:52:09Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/510","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/events","html_url":"https://github.com/octokit/octokit.rb/issues/510","id":43755109,"number":510,"title":"Creating a pull request using Octokit fails","user":{"login":"AdrienGiboire","id":394860,"avatar_url":"https://avatars.githubusercontent.com/u/394860?v=2","gravatar_id":"","url":"https://api.github.com/users/AdrienGiboire","html_url":"https://github.com/AdrienGiboire","followers_url":"https://api.github.com/users/AdrienGiboire/followers","following_url":"https://api.github.com/users/AdrienGiboire/following{/other_user}","gists_url":"https://api.github.com/users/AdrienGiboire/gists{/gist_id}","starred_url":"https://api.github.com/users/AdrienGiboire/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AdrienGiboire/subscriptions","organizations_url":"https://api.github.com/users/AdrienGiboire/orgs","repos_url":"https://api.github.com/users/AdrienGiboire/repos","events_url":"https://api.github.com/users/AdrienGiboire/events{/privacy}","received_events_url":"https://api.github.com/users/AdrienGiboire/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"milestone":null,"comments":12,"created_at":"2014-09-24T11:44:53Z","updated_at":"2014-09-24T16:47:40Z","closed_at":null,"body":"I develop the `git-pulls` gem. Sources are available here: https://github.com/schacon/git-pulls/\r\n\r\nThis is to say that everything is working fine. But yesterday, I started working on a new feature. I want to allow user to open/close pull requests using the gem.\r\n\r\nHere is what I currently have:\r\n\r\n```ruby\r\n      def open\r\n        while arg = @args.shift\r\n          case arg\r\n          when '-t'\r\n            title = @args.shift\r\n          when '-m'\r\n            description = @args.shift\r\n          end\r\n        end\r\n    \r\n        head = File.read(File.join(GIT_PATH.call, '/HEAD')).sub!('ref: ', '')\r\n        base = \"refs/remotes/#{GIT_REMOTE}/master\"\r\n    \r\n        url_memo = Hash.new { |h,k| h[k]=[] }\r\n        git('remote -v').to_s.split(\"\\n\").map do |line|\r\n          next if line !~ /^(.+?)\\t(.+) \\(/\r\n          name, url = $1, $2\r\n          url_memo[name] << url\r\n        end\r\n        url = url_memo[GIT_REMOTE].uniq[0]\r\n        if url\r\n          repo = url.scan(/^git@github.com:(.+)\\.git/)[0][0]\r\n    \r\n          Octokit.create_pull_request(repo, base, head, title, description)\r\n        end\r\n      end\r\n```\r\n\r\nFor some reasons, the PR creation doesn't work. I keep getting this error:\r\n\r\n    $ ./bin/git-pulls open -t \"Fake PR\" -m \"Fake PR description\"\r\n\r\n    /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/schacon/git-pulls/pulls: 404 - Not Found // See: https://developer.github.com/v3 (Octokit::NotFound)\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:9:in `block in call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:57:in `on_complete'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:177:in `post'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/sawyer-0.5.5/lib/sawyer/agent.rb:94:in `call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client.rb:339:in `request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client.rb:144:in `post'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client/pull_requests.rb:66:in `create_pull_request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit.rb:27:in `method_missing'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:184:in `open'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:34:in `run'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:21:in `start'\r\n        from ./bin/git-pulls:6:in `<main>'\r\n\r\nYet, https://api.github.com/repos/schacon/git-pulls/pulls exists and according to the [documentation](https://developer.github.com/v3/pulls/#create-a-pull-request) it doesn't seem to be violating any rules.\r\n\r\nCurrently running:\r\n\r\n* Ruby 2.1.2\r\n* Octokit 3.3.1\r\n\r\nParameters sent to the `Octokit#create_pull_request` in this example are:\r\n\r\n* `repo` equals `schacon/git-pulls`\r\n* `base` equals `refs/remotes/origin/master`\r\n* `head` equals `refs/heads/feature/open_close_commands`\r\n* `title` equals `Fake PR`\r\n* `description` equals `Fake PR description`\r\n\r\nAny hints?"}},{"id":169601281,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/169601281","actor":{"login":"AdrienGiboire","id":394860,"avatar_url":"https://avatars.githubusercontent.com/u/394860?v=2","gravatar_id":"","url":"https://api.github.com/users/AdrienGiboire","html_url":"https://github.com/AdrienGiboire","followers_url":"https://api.github.com/users/AdrienGiboire/followers","following_url":"https://api.github.com/users/AdrienGiboire/following{/other_user}","gists_url":"https://api.github.com/users/AdrienGiboire/gists{/gist_id}","starred_url":"https://api.github.com/users/AdrienGiboire/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AdrienGiboire/subscriptions","organizations_url":"https://api.github.com/users/AdrienGiboire/orgs","repos_url":"https://api.github.com/users/AdrienGiboire/repos","events_url":"https://api.github.com/users/AdrienGiboire/events{/privacy}","received_events_url":"https://api.github.com/users/AdrienGiboire/received_events","type":"User","site_admin":false},"event":"mentioned","commit_id":null,"created_at":"2014-09-24T13:52:09Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/510","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/events","html_url":"https://github.com/octokit/octokit.rb/issues/510","id":43755109,"number":510,"title":"Creating a pull request using Octokit fails","user":{"login":"AdrienGiboire","id":394860,"avatar_url":"https://avatars.githubusercontent.com/u/394860?v=2","gravatar_id":"","url":"https://api.github.com/users/AdrienGiboire","html_url":"https://github.com/AdrienGiboire","followers_url":"https://api.github.com/users/AdrienGiboire/followers","following_url":"https://api.github.com/users/AdrienGiboire/following{/other_user}","gists_url":"https://api.github.com/users/AdrienGiboire/gists{/gist_id}","starred_url":"https://api.github.com/users/AdrienGiboire/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AdrienGiboire/subscriptions","organizations_url":"https://api.github.com/users/AdrienGiboire/orgs","repos_url":"https://api.github.com/users/AdrienGiboire/repos","events_url":"https://api.github.com/users/AdrienGiboire/events{/privacy}","received_events_url":"https://api.github.com/users/AdrienGiboire/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"milestone":null,"comments":12,"created_at":"2014-09-24T11:44:53Z","updated_at":"2014-09-24T16:47:40Z","closed_at":null,"body":"I develop the `git-pulls` gem. Sources are available here: https://github.com/schacon/git-pulls/\r\n\r\nThis is to say that everything is working fine. But yesterday, I started working on a new feature. I want to allow user to open/close pull requests using the gem.\r\n\r\nHere is what I currently have:\r\n\r\n```ruby\r\n      def open\r\n        while arg = @args.shift\r\n          case arg\r\n          when '-t'\r\n            title = @args.shift\r\n          when '-m'\r\n            description = @args.shift\r\n          end\r\n        end\r\n    \r\n        head = File.read(File.join(GIT_PATH.call, '/HEAD')).sub!('ref: ', '')\r\n        base = \"refs/remotes/#{GIT_REMOTE}/master\"\r\n    \r\n        url_memo = Hash.new { |h,k| h[k]=[] }\r\n        git('remote -v').to_s.split(\"\\n\").map do |line|\r\n          next if line !~ /^(.+?)\\t(.+) \\(/\r\n          name, url = $1, $2\r\n          url_memo[name] << url\r\n        end\r\n        url = url_memo[GIT_REMOTE].uniq[0]\r\n        if url\r\n          repo = url.scan(/^git@github.com:(.+)\\.git/)[0][0]\r\n    \r\n          Octokit.create_pull_request(repo, base, head, title, description)\r\n        end\r\n      end\r\n```\r\n\r\nFor some reasons, the PR creation doesn't work. I keep getting this error:\r\n\r\n    $ ./bin/git-pulls open -t \"Fake PR\" -m \"Fake PR description\"\r\n\r\n    /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/schacon/git-pulls/pulls: 404 - Not Found // See: https://developer.github.com/v3 (Octokit::NotFound)\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:9:in `block in call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:57:in `on_complete'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:177:in `post'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/sawyer-0.5.5/lib/sawyer/agent.rb:94:in `call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client.rb:339:in `request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client.rb:144:in `post'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client/pull_requests.rb:66:in `create_pull_request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit.rb:27:in `method_missing'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:184:in `open'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:34:in `run'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:21:in `start'\r\n        from ./bin/git-pulls:6:in `<main>'\r\n\r\nYet, https://api.github.com/repos/schacon/git-pulls/pulls exists and according to the [documentation](https://developer.github.com/v3/pulls/#create-a-pull-request) it doesn't seem to be violating any rules.\r\n\r\nCurrently running:\r\n\r\n* Ruby 2.1.2\r\n* Octokit 3.3.1\r\n\r\nParameters sent to the `Octokit#create_pull_request` in this example are:\r\n\r\n* `repo` equals `schacon/git-pulls`\r\n* `base` equals `refs/remotes/origin/master`\r\n* `head` equals `refs/heads/feature/open_close_commands`\r\n* `title` equals `Fake PR`\r\n* `description` equals `Fake PR description`\r\n\r\nAny hints?"}},{"id":169597137,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/169597137","actor":{"login":"pengwynn","id":865,"avatar_url":"https://avatars.githubusercontent.com/u/865?v=2","gravatar_id":"","url":"https://api.github.com/users/pengwynn","html_url":"https://github.com/pengwynn","followers_url":"https://api.github.com/users/pengwynn/followers","following_url":"https://api.github.com/users/pengwynn/following{/other_user}","gists_url":"https://api.github.com/users/pengwynn/gists{/gist_id}","starred_url":"https://api.github.com/users/pengwynn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/pengwynn/subscriptions","organizations_url":"https://api.github.com/users/pengwynn/orgs","repos_url":"https://api.github.com/users/pengwynn/repos","events_url":"https://api.github.com/users/pengwynn/events{/privacy}","received_events_url":"https://api.github.com/users/pengwynn/received_events","type":"User","site_admin":true},"event":"subscribed","commit_id":null,"created_at":"2014-09-24T13:44:19Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/510","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/events","html_url":"https://github.com/octokit/octokit.rb/issues/510","id":43755109,"number":510,"title":"Creating a pull request using Octokit fails","user":{"login":"AdrienGiboire","id":394860,"avatar_url":"https://avatars.githubusercontent.com/u/394860?v=2","gravatar_id":"","url":"https://api.github.com/users/AdrienGiboire","html_url":"https://github.com/AdrienGiboire","followers_url":"https://api.github.com/users/AdrienGiboire/followers","following_url":"https://api.github.com/users/AdrienGiboire/following{/other_user}","gists_url":"https://api.github.com/users/AdrienGiboire/gists{/gist_id}","starred_url":"https://api.github.com/users/AdrienGiboire/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AdrienGiboire/subscriptions","organizations_url":"https://api.github.com/users/AdrienGiboire/orgs","repos_url":"https://api.github.com/users/AdrienGiboire/repos","events_url":"https://api.github.com/users/AdrienGiboire/events{/privacy}","received_events_url":"https://api.github.com/users/AdrienGiboire/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"milestone":null,"comments":12,"created_at":"2014-09-24T11:44:53Z","updated_at":"2014-09-24T16:47:40Z","closed_at":null,"body":"I develop the `git-pulls` gem. Sources are available here: https://github.com/schacon/git-pulls/\r\n\r\nThis is to say that everything is working fine. But yesterday, I started working on a new feature. I want to allow user to open/close pull requests using the gem.\r\n\r\nHere is what I currently have:\r\n\r\n```ruby\r\n      def open\r\n        while arg = @args.shift\r\n          case arg\r\n          when '-t'\r\n            title = @args.shift\r\n          when '-m'\r\n            description = @args.shift\r\n          end\r\n        end\r\n    \r\n        head = File.read(File.join(GIT_PATH.call, '/HEAD')).sub!('ref: ', '')\r\n        base = \"refs/remotes/#{GIT_REMOTE}/master\"\r\n    \r\n        url_memo = Hash.new { |h,k| h[k]=[] }\r\n        git('remote -v').to_s.split(\"\\n\").map do |line|\r\n          next if line !~ /^(.+?)\\t(.+) \\(/\r\n          name, url = $1, $2\r\n          url_memo[name] << url\r\n        end\r\n        url = url_memo[GIT_REMOTE].uniq[0]\r\n        if url\r\n          repo = url.scan(/^git@github.com:(.+)\\.git/)[0][0]\r\n    \r\n          Octokit.create_pull_request(repo, base, head, title, description)\r\n        end\r\n      end\r\n```\r\n\r\nFor some reasons, the PR creation doesn't work. I keep getting this error:\r\n\r\n    $ ./bin/git-pulls open -t \"Fake PR\" -m \"Fake PR description\"\r\n\r\n    /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/schacon/git-pulls/pulls: 404 - Not Found // See: https://developer.github.com/v3 (Octokit::NotFound)\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:9:in `block in call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:57:in `on_complete'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:177:in `post'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/sawyer-0.5.5/lib/sawyer/agent.rb:94:in `call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client.rb:339:in `request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client.rb:144:in `post'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client/pull_requests.rb:66:in `create_pull_request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit.rb:27:in `method_missing'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:184:in `open'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:34:in `run'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:21:in `start'\r\n        from ./bin/git-pulls:6:in `<main>'\r\n\r\nYet, https://api.github.com/repos/schacon/git-pulls/pulls exists and according to the [documentation](https://developer.github.com/v3/pulls/#create-a-pull-request) it doesn't seem to be violating any rules.\r\n\r\nCurrently running:\r\n\r\n* Ruby 2.1.2\r\n* Octokit 3.3.1\r\n\r\nParameters sent to the `Octokit#create_pull_request` in this example are:\r\n\r\n* `repo` equals `schacon/git-pulls`\r\n* `base` equals `refs/remotes/origin/master`\r\n* `head` equals `refs/heads/feature/open_close_commands`\r\n* `title` equals `Fake PR`\r\n* `description` equals `Fake PR description`\r\n\r\nAny hints?"}},{"id":169597136,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/169597136","actor":{"login":"pengwynn","id":865,"avatar_url":"https://avatars.githubusercontent.com/u/865?v=2","gravatar_id":"","url":"https://api.github.com/users/pengwynn","html_url":"https://github.com/pengwynn","followers_url":"https://api.github.com/users/pengwynn/followers","following_url":"https://api.github.com/users/pengwynn/following{/other_user}","gists_url":"https://api.github.com/users/pengwynn/gists{/gist_id}","starred_url":"https://api.github.com/users/pengwynn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/pengwynn/subscriptions","organizations_url":"https://api.github.com/users/pengwynn/orgs","repos_url":"https://api.github.com/users/pengwynn/repos","events_url":"https://api.github.com/users/pengwynn/events{/privacy}","received_events_url":"https://api.github.com/users/pengwynn/received_events","type":"User","site_admin":true},"event":"mentioned","commit_id":null,"created_at":"2014-09-24T13:44:19Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/510","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/events","html_url":"https://github.com/octokit/octokit.rb/issues/510","id":43755109,"number":510,"title":"Creating a pull request using Octokit fails","user":{"login":"AdrienGiboire","id":394860,"avatar_url":"https://avatars.githubusercontent.com/u/394860?v=2","gravatar_id":"","url":"https://api.github.com/users/AdrienGiboire","html_url":"https://github.com/AdrienGiboire","followers_url":"https://api.github.com/users/AdrienGiboire/followers","following_url":"https://api.github.com/users/AdrienGiboire/following{/other_user}","gists_url":"https://api.github.com/users/AdrienGiboire/gists{/gist_id}","starred_url":"https://api.github.com/users/AdrienGiboire/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AdrienGiboire/subscriptions","organizations_url":"https://api.github.com/users/AdrienGiboire/orgs","repos_url":"https://api.github.com/users/AdrienGiboire/repos","events_url":"https://api.github.com/users/AdrienGiboire/events{/privacy}","received_events_url":"https://api.github.com/users/AdrienGiboire/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"milestone":null,"comments":12,"created_at":"2014-09-24T11:44:53Z","updated_at":"2014-09-24T16:47:40Z","closed_at":null,"body":"I develop the `git-pulls` gem. Sources are available here: https://github.com/schacon/git-pulls/\r\n\r\nThis is to say that everything is working fine. But yesterday, I started working on a new feature. I want to allow user to open/close pull requests using the gem.\r\n\r\nHere is what I currently have:\r\n\r\n```ruby\r\n      def open\r\n        while arg = @args.shift\r\n          case arg\r\n          when '-t'\r\n            title = @args.shift\r\n          when '-m'\r\n            description = @args.shift\r\n          end\r\n        end\r\n    \r\n        head = File.read(File.join(GIT_PATH.call, '/HEAD')).sub!('ref: ', '')\r\n        base = \"refs/remotes/#{GIT_REMOTE}/master\"\r\n    \r\n        url_memo = Hash.new { |h,k| h[k]=[] }\r\n        git('remote -v').to_s.split(\"\\n\").map do |line|\r\n          next if line !~ /^(.+?)\\t(.+) \\(/\r\n          name, url = $1, $2\r\n          url_memo[name] << url\r\n        end\r\n        url = url_memo[GIT_REMOTE].uniq[0]\r\n        if url\r\n          repo = url.scan(/^git@github.com:(.+)\\.git/)[0][0]\r\n    \r\n          Octokit.create_pull_request(repo, base, head, title, description)\r\n        end\r\n      end\r\n```\r\n\r\nFor some reasons, the PR creation doesn't work. I keep getting this error:\r\n\r\n    $ ./bin/git-pulls open -t \"Fake PR\" -m \"Fake PR description\"\r\n\r\n    /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/schacon/git-pulls/pulls: 404 - Not Found // See: https://developer.github.com/v3 (Octokit::NotFound)\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:9:in `block in call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:57:in `on_complete'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:177:in `post'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/sawyer-0.5.5/lib/sawyer/agent.rb:94:in `call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client.rb:339:in `request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client.rb:144:in `post'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client/pull_requests.rb:66:in `create_pull_request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit.rb:27:in `method_missing'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:184:in `open'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:34:in `run'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:21:in `start'\r\n        from ./bin/git-pulls:6:in `<main>'\r\n\r\nYet, https://api.github.com/repos/schacon/git-pulls/pulls exists and according to the [documentation](https://developer.github.com/v3/pulls/#create-a-pull-request) it doesn't seem to be violating any rules.\r\n\r\nCurrently running:\r\n\r\n* Ruby 2.1.2\r\n* Octokit 3.3.1\r\n\r\nParameters sent to the `Octokit#create_pull_request` in this example are:\r\n\r\n* `repo` equals `schacon/git-pulls`\r\n* `base` equals `refs/remotes/origin/master`\r\n* `head` equals `refs/heads/feature/open_close_commands`\r\n* `title` equals `Fake PR`\r\n* `description` equals `Fake PR description`\r\n\r\nAny hints?"}},{"id":169594406,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/169594406","actor":{"login":"AdrienGiboire","id":394860,"avatar_url":"https://avatars.githubusercontent.com/u/394860?v=2","gravatar_id":"","url":"https://api.github.com/users/AdrienGiboire","html_url":"https://github.com/AdrienGiboire","followers_url":"https://api.github.com/users/AdrienGiboire/followers","following_url":"https://api.github.com/users/AdrienGiboire/following{/other_user}","gists_url":"https://api.github.com/users/AdrienGiboire/gists{/gist_id}","starred_url":"https://api.github.com/users/AdrienGiboire/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AdrienGiboire/subscriptions","organizations_url":"https://api.github.com/users/AdrienGiboire/orgs","repos_url":"https://api.github.com/users/AdrienGiboire/repos","events_url":"https://api.github.com/users/AdrienGiboire/events{/privacy}","received_events_url":"https://api.github.com/users/AdrienGiboire/received_events","type":"User","site_admin":false},"event":"subscribed","commit_id":null,"created_at":"2014-09-24T13:38:57Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/510","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/events","html_url":"https://github.com/octokit/octokit.rb/issues/510","id":43755109,"number":510,"title":"Creating a pull request using Octokit fails","user":{"login":"AdrienGiboire","id":394860,"avatar_url":"https://avatars.githubusercontent.com/u/394860?v=2","gravatar_id":"","url":"https://api.github.com/users/AdrienGiboire","html_url":"https://github.com/AdrienGiboire","followers_url":"https://api.github.com/users/AdrienGiboire/followers","following_url":"https://api.github.com/users/AdrienGiboire/following{/other_user}","gists_url":"https://api.github.com/users/AdrienGiboire/gists{/gist_id}","starred_url":"https://api.github.com/users/AdrienGiboire/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AdrienGiboire/subscriptions","organizations_url":"https://api.github.com/users/AdrienGiboire/orgs","repos_url":"https://api.github.com/users/AdrienGiboire/repos","events_url":"https://api.github.com/users/AdrienGiboire/events{/privacy}","received_events_url":"https://api.github.com/users/AdrienGiboire/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"milestone":null,"comments":12,"created_at":"2014-09-24T11:44:53Z","updated_at":"2014-09-24T16:47:40Z","closed_at":null,"body":"I develop the `git-pulls` gem. Sources are available here: https://github.com/schacon/git-pulls/\r\n\r\nThis is to say that everything is working fine. But yesterday, I started working on a new feature. I want to allow user to open/close pull requests using the gem.\r\n\r\nHere is what I currently have:\r\n\r\n```ruby\r\n      def open\r\n        while arg = @args.shift\r\n          case arg\r\n          when '-t'\r\n            title = @args.shift\r\n          when '-m'\r\n            description = @args.shift\r\n          end\r\n        end\r\n    \r\n        head = File.read(File.join(GIT_PATH.call, '/HEAD')).sub!('ref: ', '')\r\n        base = \"refs/remotes/#{GIT_REMOTE}/master\"\r\n    \r\n        url_memo = Hash.new { |h,k| h[k]=[] }\r\n        git('remote -v').to_s.split(\"\\n\").map do |line|\r\n          next if line !~ /^(.+?)\\t(.+) \\(/\r\n          name, url = $1, $2\r\n          url_memo[name] << url\r\n        end\r\n        url = url_memo[GIT_REMOTE].uniq[0]\r\n        if url\r\n          repo = url.scan(/^git@github.com:(.+)\\.git/)[0][0]\r\n    \r\n          Octokit.create_pull_request(repo, base, head, title, description)\r\n        end\r\n      end\r\n```\r\n\r\nFor some reasons, the PR creation doesn't work. I keep getting this error:\r\n\r\n    $ ./bin/git-pulls open -t \"Fake PR\" -m \"Fake PR description\"\r\n\r\n    /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/schacon/git-pulls/pulls: 404 - Not Found // See: https://developer.github.com/v3 (Octokit::NotFound)\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:9:in `block in call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:57:in `on_complete'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:177:in `post'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/sawyer-0.5.5/lib/sawyer/agent.rb:94:in `call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client.rb:339:in `request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client.rb:144:in `post'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client/pull_requests.rb:66:in `create_pull_request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit.rb:27:in `method_missing'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:184:in `open'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:34:in `run'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:21:in `start'\r\n        from ./bin/git-pulls:6:in `<main>'\r\n\r\nYet, https://api.github.com/repos/schacon/git-pulls/pulls exists and according to the [documentation](https://developer.github.com/v3/pulls/#create-a-pull-request) it doesn't seem to be violating any rules.\r\n\r\nCurrently running:\r\n\r\n* Ruby 2.1.2\r\n* Octokit 3.3.1\r\n\r\nParameters sent to the `Octokit#create_pull_request` in this example are:\r\n\r\n* `repo` equals `schacon/git-pulls`\r\n* `base` equals `refs/remotes/origin/master`\r\n* `head` equals `refs/heads/feature/open_close_commands`\r\n* `title` equals `Fake PR`\r\n* `description` equals `Fake PR description`\r\n\r\nAny hints?"}},{"id":169594405,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/169594405","actor":{"login":"AdrienGiboire","id":394860,"avatar_url":"https://avatars.githubusercontent.com/u/394860?v=2","gravatar_id":"","url":"https://api.github.com/users/AdrienGiboire","html_url":"https://github.com/AdrienGiboire","followers_url":"https://api.github.com/users/AdrienGiboire/followers","following_url":"https://api.github.com/users/AdrienGiboire/following{/other_user}","gists_url":"https://api.github.com/users/AdrienGiboire/gists{/gist_id}","starred_url":"https://api.github.com/users/AdrienGiboire/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AdrienGiboire/subscriptions","organizations_url":"https://api.github.com/users/AdrienGiboire/orgs","repos_url":"https://api.github.com/users/AdrienGiboire/repos","events_url":"https://api.github.com/users/AdrienGiboire/events{/privacy}","received_events_url":"https://api.github.com/users/AdrienGiboire/received_events","type":"User","site_admin":false},"event":"mentioned","commit_id":null,"created_at":"2014-09-24T13:38:57Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/510","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/510/events","html_url":"https://github.com/octokit/octokit.rb/issues/510","id":43755109,"number":510,"title":"Creating a pull request using Octokit fails","user":{"login":"AdrienGiboire","id":394860,"avatar_url":"https://avatars.githubusercontent.com/u/394860?v=2","gravatar_id":"","url":"https://api.github.com/users/AdrienGiboire","html_url":"https://github.com/AdrienGiboire","followers_url":"https://api.github.com/users/AdrienGiboire/followers","following_url":"https://api.github.com/users/AdrienGiboire/following{/other_user}","gists_url":"https://api.github.com/users/AdrienGiboire/gists{/gist_id}","starred_url":"https://api.github.com/users/AdrienGiboire/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AdrienGiboire/subscriptions","organizations_url":"https://api.github.com/users/AdrienGiboire/orgs","repos_url":"https://api.github.com/users/AdrienGiboire/repos","events_url":"https://api.github.com/users/AdrienGiboire/events{/privacy}","received_events_url":"https://api.github.com/users/AdrienGiboire/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"milestone":null,"comments":12,"created_at":"2014-09-24T11:44:53Z","updated_at":"2014-09-24T16:47:40Z","closed_at":null,"body":"I develop the `git-pulls` gem. Sources are available here: https://github.com/schacon/git-pulls/\r\n\r\nThis is to say that everything is working fine. But yesterday, I started working on a new feature. I want to allow user to open/close pull requests using the gem.\r\n\r\nHere is what I currently have:\r\n\r\n```ruby\r\n      def open\r\n        while arg = @args.shift\r\n          case arg\r\n          when '-t'\r\n            title = @args.shift\r\n          when '-m'\r\n            description = @args.shift\r\n          end\r\n        end\r\n    \r\n        head = File.read(File.join(GIT_PATH.call, '/HEAD')).sub!('ref: ', '')\r\n        base = \"refs/remotes/#{GIT_REMOTE}/master\"\r\n    \r\n        url_memo = Hash.new { |h,k| h[k]=[] }\r\n        git('remote -v').to_s.split(\"\\n\").map do |line|\r\n          next if line !~ /^(.+?)\\t(.+) \\(/\r\n          name, url = $1, $2\r\n          url_memo[name] << url\r\n        end\r\n        url = url_memo[GIT_REMOTE].uniq[0]\r\n        if url\r\n          repo = url.scan(/^git@github.com:(.+)\\.git/)[0][0]\r\n    \r\n          Octokit.create_pull_request(repo, base, head, title, description)\r\n        end\r\n      end\r\n```\r\n\r\nFor some reasons, the PR creation doesn't work. I keep getting this error:\r\n\r\n    $ ./bin/git-pulls open -t \"Fake PR\" -m \"Fake PR description\"\r\n\r\n    /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/schacon/git-pulls/pulls: 404 - Not Found // See: https://developer.github.com/v3 (Octokit::NotFound)\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:9:in `block in call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:57:in `on_complete'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:177:in `post'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/sawyer-0.5.5/lib/sawyer/agent.rb:94:in `call'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client.rb:339:in `request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client.rb:144:in `post'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client/pull_requests.rb:66:in `create_pull_request'\r\n        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit.rb:27:in `method_missing'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:184:in `open'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:34:in `run'\r\n        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:21:in `start'\r\n        from ./bin/git-pulls:6:in `<main>'\r\n\r\nYet, https://api.github.com/repos/schacon/git-pulls/pulls exists and according to the [documentation](https://developer.github.com/v3/pulls/#create-a-pull-request) it doesn't seem to be violating any rules.\r\n\r\nCurrently running:\r\n\r\n* Ruby 2.1.2\r\n* Octokit 3.3.1\r\n\r\nParameters sent to the `Octokit#create_pull_request` in this example are:\r\n\r\n* `repo` equals `schacon/git-pulls`\r\n* `base` equals `refs/remotes/origin/master`\r\n* `head` equals `refs/heads/feature/open_close_commands`\r\n* `title` equals `Fake PR`\r\n* `description` equals `Fake PR description`\r\n\r\nAny hints?"}},{"id":168319239,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/168319239","actor":{"login":"aeden","id":8556,"avatar_url":"https://avatars.githubusercontent.com/u/8556?v=2","gravatar_id":"","url":"https://api.github.com/users/aeden","html_url":"https://github.com/aeden","followers_url":"https://api.github.com/users/aeden/followers","following_url":"https://api.github.com/users/aeden/following{/other_user}","gists_url":"https://api.github.com/users/aeden/gists{/gist_id}","starred_url":"https://api.github.com/users/aeden/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/aeden/subscriptions","organizations_url":"https://api.github.com/users/aeden/orgs","repos_url":"https://api.github.com/users/aeden/repos","events_url":"https://api.github.com/users/aeden/events{/privacy}","received_events_url":"https://api.github.com/users/aeden/received_events","type":"User","site_admin":false},"event":"closed","commit_id":null,"created_at":"2014-09-22T08:29:30Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/508","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/508/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/508/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/508/events","html_url":"https://github.com/octokit/octokit.rb/issues/508","id":43434084,"number":508,"title":"update_content raising an error","user":{"login":"aeden","id":8556,"avatar_url":"https://avatars.githubusercontent.com/u/8556?v=2","gravatar_id":"","url":"https://api.github.com/users/aeden","html_url":"https://github.com/aeden","followers_url":"https://api.github.com/users/aeden/followers","following_url":"https://api.github.com/users/aeden/following{/other_user}","gists_url":"https://api.github.com/users/aeden/gists{/gist_id}","starred_url":"https://api.github.com/users/aeden/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/aeden/subscriptions","organizations_url":"https://api.github.com/users/aeden/orgs","repos_url":"https://api.github.com/users/aeden/repos","events_url":"https://api.github.com/users/aeden/events{/privacy}","received_events_url":"https://api.github.com/users/aeden/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"milestone":null,"comments":1,"created_at":"2014-09-22T08:01:26Z","updated_at":"2014-09-22T08:29:30Z","closed_at":"2014-09-22T08:29:30Z","body":"I'm trying to update content using the following:\r\n\r\n```ruby\r\ngithub_client.update_contents(repository_identifier, zone_path, \"Zone updated\", zone_sha(zone_path), zone_json(domain), branch: \"master\")\r\n```\r\n\r\nWhere `zone_sha(zone_path)` returns the current SHA for the path `zones/test-zone-2.com.json` and `zone_json(domain)` returns a JSON string representing the zone data. The result is:\r\n\r\n```\r\nOctokit::UnprocessableEntity: PUT https://api.github.com/repos/aeden/zones/contents/zones/test-zone-2.com.json: 422 - Invalid request.\r\n\r\nExpected data to be of type \"string\"; value was: {\"path\"=>\"zones/test-zone-2.com.json\", \"mode\"=>\"100644\", \"type\"=>\"blob\", \"sha\"=>\"acdd57c3acca7a7692912a9c00c0dce483bf5734\", \"size\"=>259, \"url\"=>\"https://api.github.com/repos/aeden/zones/git/blobs/acdd57c3acca7a7692912a9c00c0dce483bf5734\"}. // See: https://developer.github.com/v3/repos/contents/\r\n\tfrom /Users/anthonyeden/.rvm/gems/ruby-2.1.1@dnsimple/gems/octokit-3.3.1/lib/octokit/response/raise_error.rb:16:in `on_complete'\r\n\tfrom /Users/anthonyeden/.rvm/gems/ruby-2.1.1@dnsimple/gems/faraday-0.9.0/lib/faraday/response.rb:9:in `block in call'\r\n\tfrom /Users/anthonyeden/.rvm/gems/ruby-2.1.1@dnsimple/gems/faraday-0.9.0/lib/faraday/response.rb:57:in `on_complete'\r\n\tfrom /Users/anthonyeden/.rvm/gems/ruby-2.1.1@dnsimple/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'\r\n\tfrom /Users/anthonyeden/.rvm/gems/ruby-2.1.1@dnsimple/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'\r\n\tfrom /Users/anthonyeden/.rvm/gems/ruby-2.1.1@dnsimple/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'\r\n\tfrom /Users/anthonyeden/.rvm/gems/ruby-2.1.1@dnsimple/gems/faraday-0.9.0/lib/faraday/connection.rb:177:in `put'\r\n\tfrom /Users/anthonyeden/.rvm/gems/ruby-2.1.1@dnsimple/gems/sawyer-0.5.5/lib/sawyer/agent.rb:94:in `call'\r\n\tfrom /Users/anthonyeden/.rvm/gems/ruby-2.1.1@dnsimple/gems/octokit-3.3.1/lib/octokit/client.rb:339:in `request'\r\n\tfrom /Users/anthonyeden/.rvm/gems/ruby-2.1.1@dnsimple/gems/octokit-3.3.1/lib/octokit/client.rb:153:in `put'\r\n\tfrom /Users/anthonyeden/.rvm/gems/ruby-2.1.1@dnsimple/gems/octokit-3.3.1/lib/octokit/client/contents.rb:81:in `create_contents'\r\n\tfrom /Users/anthonyeden/.rvm/gems/ruby-2.1.1@dnsimple/gems/octokit-3.3.1/lib/octokit/client/contents.rb:114:in `update_contents'\r\n```\r\n\r\nCalling `create_contents` for new content worked fine."}},{"id":165459244,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/165459244","actor":{"login":"krzyzak","id":185015,"avatar_url":"https://avatars.githubusercontent.com/u/185015?v=2","gravatar_id":"","url":"https://api.github.com/users/krzyzak","html_url":"https://github.com/krzyzak","followers_url":"https://api.github.com/users/krzyzak/followers","following_url":"https://api.github.com/users/krzyzak/following{/other_user}","gists_url":"https://api.github.com/users/krzyzak/gists{/gist_id}","starred_url":"https://api.github.com/users/krzyzak/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/krzyzak/subscriptions","organizations_url":"https://api.github.com/users/krzyzak/orgs","repos_url":"https://api.github.com/users/krzyzak/repos","events_url":"https://api.github.com/users/krzyzak/events{/privacy}","received_events_url":"https://api.github.com/users/krzyzak/received_events","type":"User","site_admin":false},"event":"subscribed","commit_id":null,"created_at":"2014-09-15T13:28:15Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/496","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/496/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/496/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/496/events","html_url":"https://github.com/octokit/octokit.rb/pull/496","id":37889272,"number":496,"title":"Enhanced Octokit::TooManyRequests exception","user":{"login":"krzyzak","id":185015,"avatar_url":"https://avatars.githubusercontent.com/u/185015?v=2","gravatar_id":"","url":"https://api.github.com/users/krzyzak","html_url":"https://github.com/krzyzak","followers_url":"https://api.github.com/users/krzyzak/followers","following_url":"https://api.github.com/users/krzyzak/following{/other_user}","gists_url":"https://api.github.com/users/krzyzak/gists{/gist_id}","starred_url":"https://api.github.com/users/krzyzak/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/krzyzak/subscriptions","organizations_url":"https://api.github.com/users/krzyzak/orgs","repos_url":"https://api.github.com/users/krzyzak/repos","events_url":"https://api.github.com/users/krzyzak/events{/privacy}","received_events_url":"https://api.github.com/users/krzyzak/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"milestone":null,"comments":4,"created_at":"2014-07-15T14:36:19Z","updated_at":"2014-09-15T13:28:15Z","closed_at":null,"pull_request":{"url":"https://api.github.com/repos/octokit/octokit.rb/pulls/496","html_url":"https://github.com/octokit/octokit.rb/pull/496","diff_url":"https://github.com/octokit/octokit.rb/pull/496.diff","patch_url":"https://github.com/octokit/octokit.rb/pull/496.patch"},"body":"Hi,\r\n\r\nWhen I was trying to catch ```Octokit::TooManyRequests``` exception in my application, I found that there’s no way to return my current rate limit, as well as when limit will be reset.\r\n\r\nBefore, I had to do something like this:\r\n```ruby \r\nbegin\r\n  Octokit.repo(\"rails/rails\")\r\nrescue Octokit::TooManyRequests => e\r\n  reset = e.instance_variable_get(:@response).response_headers[\"x-ratelimit-reset\"].to_i\r\n  sleep Time.at(reset) - Time.now\r\n  retry\r\nend\r\n```\r\n\r\nThis code is bad, and I feel bad that I wrote it ;)\r\n\r\nWith my patch, I don’t have to break encapsulation and write code like this:\r\n\r\n```ruby\r\nbegin\r\n  Octokit.repo(\"rails/rails\")\r\nrescue Octokit::TooManyRequests => e\r\n  sleep e.limit_resets_at - Time.now\r\n  retry\r\nend\r\n```\r\n"}},{"id":165459243,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/165459243","actor":{"login":"krzyzak","id":185015,"avatar_url":"https://avatars.githubusercontent.com/u/185015?v=2","gravatar_id":"","url":"https://api.github.com/users/krzyzak","html_url":"https://github.com/krzyzak","followers_url":"https://api.github.com/users/krzyzak/followers","following_url":"https://api.github.com/users/krzyzak/following{/other_user}","gists_url":"https://api.github.com/users/krzyzak/gists{/gist_id}","starred_url":"https://api.github.com/users/krzyzak/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/krzyzak/subscriptions","organizations_url":"https://api.github.com/users/krzyzak/orgs","repos_url":"https://api.github.com/users/krzyzak/repos","events_url":"https://api.github.com/users/krzyzak/events{/privacy}","received_events_url":"https://api.github.com/users/krzyzak/received_events","type":"User","site_admin":false},"event":"mentioned","commit_id":null,"created_at":"2014-09-15T13:28:15Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/496","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/496/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/496/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/496/events","html_url":"https://github.com/octokit/octokit.rb/pull/496","id":37889272,"number":496,"title":"Enhanced Octokit::TooManyRequests exception","user":{"login":"krzyzak","id":185015,"avatar_url":"https://avatars.githubusercontent.com/u/185015?v=2","gravatar_id":"","url":"https://api.github.com/users/krzyzak","html_url":"https://github.com/krzyzak","followers_url":"https://api.github.com/users/krzyzak/followers","following_url":"https://api.github.com/users/krzyzak/following{/other_user}","gists_url":"https://api.github.com/users/krzyzak/gists{/gist_id}","starred_url":"https://api.github.com/users/krzyzak/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/krzyzak/subscriptions","organizations_url":"https://api.github.com/users/krzyzak/orgs","repos_url":"https://api.github.com/users/krzyzak/repos","events_url":"https://api.github.com/users/krzyzak/events{/privacy}","received_events_url":"https://api.github.com/users/krzyzak/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"milestone":null,"comments":4,"created_at":"2014-07-15T14:36:19Z","updated_at":"2014-09-15T13:28:15Z","closed_at":null,"pull_request":{"url":"https://api.github.com/repos/octokit/octokit.rb/pulls/496","html_url":"https://github.com/octokit/octokit.rb/pull/496","diff_url":"https://github.com/octokit/octokit.rb/pull/496.diff","patch_url":"https://github.com/octokit/octokit.rb/pull/496.patch"},"body":"Hi,\r\n\r\nWhen I was trying to catch ```Octokit::TooManyRequests``` exception in my application, I found that there’s no way to return my current rate limit, as well as when limit will be reset.\r\n\r\nBefore, I had to do something like this:\r\n```ruby \r\nbegin\r\n  Octokit.repo(\"rails/rails\")\r\nrescue Octokit::TooManyRequests => e\r\n  reset = e.instance_variable_get(:@response).response_headers[\"x-ratelimit-reset\"].to_i\r\n  sleep Time.at(reset) - Time.now\r\n  retry\r\nend\r\n```\r\n\r\nThis code is bad, and I feel bad that I wrote it ;)\r\n\r\nWith my patch, I don’t have to break encapsulation and write code like this:\r\n\r\n```ruby\r\nbegin\r\n  Octokit.repo(\"rails/rails\")\r\nrescue Octokit::TooManyRequests => e\r\n  sleep e.limit_resets_at - Time.now\r\n  retry\r\nend\r\n```\r\n"}},{"id":165451504,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/165451504","actor":{"login":"pengwynn","id":865,"avatar_url":"https://avatars.githubusercontent.com/u/865?v=2","gravatar_id":"","url":"https://api.github.com/users/pengwynn","html_url":"https://github.com/pengwynn","followers_url":"https://api.github.com/users/pengwynn/followers","following_url":"https://api.github.com/users/pengwynn/following{/other_user}","gists_url":"https://api.github.com/users/pengwynn/gists{/gist_id}","starred_url":"https://api.github.com/users/pengwynn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/pengwynn/subscriptions","organizations_url":"https://api.github.com/users/pengwynn/orgs","repos_url":"https://api.github.com/users/pengwynn/repos","events_url":"https://api.github.com/users/pengwynn/events{/privacy}","received_events_url":"https://api.github.com/users/pengwynn/received_events","type":"User","site_admin":true},"event":"closed","commit_id":null,"created_at":"2014-09-15T13:12:12Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/507","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/507/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/507/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/507/events","html_url":"https://github.com/octokit/octokit.rb/pull/507","id":42736570,"number":507,"title":"Implement organization invitation api","user":{"login":"blt04","id":276141,"avatar_url":"https://avatars.githubusercontent.com/u/276141?v=2","gravatar_id":"","url":"https://api.github.com/users/blt04","html_url":"https://github.com/blt04","followers_url":"https://api.github.com/users/blt04/followers","following_url":"https://api.github.com/users/blt04/following{/other_user}","gists_url":"https://api.github.com/users/blt04/gists{/gist_id}","starred_url":"https://api.github.com/users/blt04/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/blt04/subscriptions","organizations_url":"https://api.github.com/users/blt04/orgs","repos_url":"https://api.github.com/users/blt04/repos","events_url":"https://api.github.com/users/blt04/events{/privacy}","received_events_url":"https://api.github.com/users/blt04/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"milestone":null,"comments":3,"created_at":"2014-09-15T01:51:32Z","updated_at":"2014-09-15T13:38:44Z","closed_at":"2014-09-15T13:12:12Z","pull_request":{"url":"https://api.github.com/repos/octokit/octokit.rb/pulls/507","html_url":"https://github.com/octokit/octokit.rb/pull/507","diff_url":"https://github.com/octokit/octokit.rb/pull/507.diff","patch_url":"https://github.com/octokit/octokit.rb/pull/507.patch"},"body":"This is an attempt at API bindings for the new Organization invitation API (https://developer.github.com/changes/2014-08-28-accepting-organization-invitations-from-the-api/).\r\n\r\nI've commented out the tests as I wasn't sure how to record a cassette that could be re-recorded by someone with access to the correct organizations."}},{"id":165451502,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/165451502","actor":{"login":"pengwynn","id":865,"avatar_url":"https://avatars.githubusercontent.com/u/865?v=2","gravatar_id":"","url":"https://api.github.com/users/pengwynn","html_url":"https://github.com/pengwynn","followers_url":"https://api.github.com/users/pengwynn/followers","following_url":"https://api.github.com/users/pengwynn/following{/other_user}","gists_url":"https://api.github.com/users/pengwynn/gists{/gist_id}","starred_url":"https://api.github.com/users/pengwynn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/pengwynn/subscriptions","organizations_url":"https://api.github.com/users/pengwynn/orgs","repos_url":"https://api.github.com/users/pengwynn/repos","events_url":"https://api.github.com/users/pengwynn/events{/privacy}","received_events_url":"https://api.github.com/users/pengwynn/received_events","type":"User","site_admin":true},"event":"merged","commit_id":"e6cf967958a690ad0cce6b2b2354f8588af0be98","created_at":"2014-09-15T13:12:12Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/507","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/507/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/507/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/507/events","html_url":"https://github.com/octokit/octokit.rb/pull/507","id":42736570,"number":507,"title":"Implement organization invitation api","user":{"login":"blt04","id":276141,"avatar_url":"https://avatars.githubusercontent.com/u/276141?v=2","gravatar_id":"","url":"https://api.github.com/users/blt04","html_url":"https://github.com/blt04","followers_url":"https://api.github.com/users/blt04/followers","following_url":"https://api.github.com/users/blt04/following{/other_user}","gists_url":"https://api.github.com/users/blt04/gists{/gist_id}","starred_url":"https://api.github.com/users/blt04/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/blt04/subscriptions","organizations_url":"https://api.github.com/users/blt04/orgs","repos_url":"https://api.github.com/users/blt04/repos","events_url":"https://api.github.com/users/blt04/events{/privacy}","received_events_url":"https://api.github.com/users/blt04/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"milestone":null,"comments":3,"created_at":"2014-09-15T01:51:32Z","updated_at":"2014-09-15T13:38:44Z","closed_at":"2014-09-15T13:12:12Z","pull_request":{"url":"https://api.github.com/repos/octokit/octokit.rb/pulls/507","html_url":"https://github.com/octokit/octokit.rb/pull/507","diff_url":"https://github.com/octokit/octokit.rb/pull/507.diff","patch_url":"https://github.com/octokit/octokit.rb/pull/507.patch"},"body":"This is an attempt at API bindings for the new Organization invitation API (https://developer.github.com/changes/2014-08-28-accepting-organization-invitations-from-the-api/).\r\n\r\nI've commented out the tests as I wasn't sure how to record a cassette that could be re-recorded by someone with access to the correct organizations."}},{"id":165451501,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/165451501","actor":{"login":"pengwynn","id":865,"avatar_url":"https://avatars.githubusercontent.com/u/865?v=2","gravatar_id":"","url":"https://api.github.com/users/pengwynn","html_url":"https://github.com/pengwynn","followers_url":"https://api.github.com/users/pengwynn/followers","following_url":"https://api.github.com/users/pengwynn/following{/other_user}","gists_url":"https://api.github.com/users/pengwynn/gists{/gist_id}","starred_url":"https://api.github.com/users/pengwynn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/pengwynn/subscriptions","organizations_url":"https://api.github.com/users/pengwynn/orgs","repos_url":"https://api.github.com/users/pengwynn/repos","events_url":"https://api.github.com/users/pengwynn/events{/privacy}","received_events_url":"https://api.github.com/users/pengwynn/received_events","type":"User","site_admin":true},"event":"referenced","commit_id":"e6cf967958a690ad0cce6b2b2354f8588af0be98","created_at":"2014-09-15T13:12:12Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/507","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/507/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/507/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/507/events","html_url":"https://github.com/octokit/octokit.rb/pull/507","id":42736570,"number":507,"title":"Implement organization invitation api","user":{"login":"blt04","id":276141,"avatar_url":"https://avatars.githubusercontent.com/u/276141?v=2","gravatar_id":"","url":"https://api.github.com/users/blt04","html_url":"https://github.com/blt04","followers_url":"https://api.github.com/users/blt04/followers","following_url":"https://api.github.com/users/blt04/following{/other_user}","gists_url":"https://api.github.com/users/blt04/gists{/gist_id}","starred_url":"https://api.github.com/users/blt04/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/blt04/subscriptions","organizations_url":"https://api.github.com/users/blt04/orgs","repos_url":"https://api.github.com/users/blt04/repos","events_url":"https://api.github.com/users/blt04/events{/privacy}","received_events_url":"https://api.github.com/users/blt04/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"milestone":null,"comments":3,"created_at":"2014-09-15T01:51:32Z","updated_at":"2014-09-15T13:38:44Z","closed_at":"2014-09-15T13:12:12Z","pull_request":{"url":"https://api.github.com/repos/octokit/octokit.rb/pulls/507","html_url":"https://github.com/octokit/octokit.rb/pull/507","diff_url":"https://github.com/octokit/octokit.rb/pull/507.diff","patch_url":"https://github.com/octokit/octokit.rb/pull/507.patch"},"body":"This is an attempt at API bindings for the new Organization invitation API (https://developer.github.com/changes/2014-08-28-accepting-organization-invitations-from-the-api/).\r\n\r\nI've commented out the tests as I wasn't sure how to record a cassette that could be re-recorded by someone with access to the correct organizations."}},{"id":165284190,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/165284190","actor":{"login":"pengwynn","id":865,"avatar_url":"https://avatars.githubusercontent.com/u/865?v=2","gravatar_id":"","url":"https://api.github.com/users/pengwynn","html_url":"https://github.com/pengwynn","followers_url":"https://api.github.com/users/pengwynn/followers","following_url":"https://api.github.com/users/pengwynn/following{/other_user}","gists_url":"https://api.github.com/users/pengwynn/gists{/gist_id}","starred_url":"https://api.github.com/users/pengwynn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/pengwynn/subscriptions","organizations_url":"https://api.github.com/users/pengwynn/orgs","repos_url":"https://api.github.com/users/pengwynn/repos","events_url":"https://api.github.com/users/pengwynn/events{/privacy}","received_events_url":"https://api.github.com/users/pengwynn/received_events","type":"User","site_admin":true},"event":"subscribed","commit_id":null,"created_at":"2014-09-15T03:06:52Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/507","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/507/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/507/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/507/events","html_url":"https://github.com/octokit/octokit.rb/pull/507","id":42736570,"number":507,"title":"Implement organization invitation api","user":{"login":"blt04","id":276141,"avatar_url":"https://avatars.githubusercontent.com/u/276141?v=2","gravatar_id":"","url":"https://api.github.com/users/blt04","html_url":"https://github.com/blt04","followers_url":"https://api.github.com/users/blt04/followers","following_url":"https://api.github.com/users/blt04/following{/other_user}","gists_url":"https://api.github.com/users/blt04/gists{/gist_id}","starred_url":"https://api.github.com/users/blt04/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/blt04/subscriptions","organizations_url":"https://api.github.com/users/blt04/orgs","repos_url":"https://api.github.com/users/blt04/repos","events_url":"https://api.github.com/users/blt04/events{/privacy}","received_events_url":"https://api.github.com/users/blt04/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"milestone":null,"comments":3,"created_at":"2014-09-15T01:51:32Z","updated_at":"2014-09-15T13:38:44Z","closed_at":"2014-09-15T13:12:12Z","pull_request":{"url":"https://api.github.com/repos/octokit/octokit.rb/pulls/507","html_url":"https://github.com/octokit/octokit.rb/pull/507","diff_url":"https://github.com/octokit/octokit.rb/pull/507.diff","patch_url":"https://github.com/octokit/octokit.rb/pull/507.patch"},"body":"This is an attempt at API bindings for the new Organization invitation API (https://developer.github.com/changes/2014-08-28-accepting-organization-invitations-from-the-api/).\r\n\r\nI've commented out the tests as I wasn't sure how to record a cassette that could be re-recorded by someone with access to the correct organizations."}},{"id":165284189,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/165284189","actor":{"login":"pengwynn","id":865,"avatar_url":"https://avatars.githubusercontent.com/u/865?v=2","gravatar_id":"","url":"https://api.github.com/users/pengwynn","html_url":"https://github.com/pengwynn","followers_url":"https://api.github.com/users/pengwynn/followers","following_url":"https://api.github.com/users/pengwynn/following{/other_user}","gists_url":"https://api.github.com/users/pengwynn/gists{/gist_id}","starred_url":"https://api.github.com/users/pengwynn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/pengwynn/subscriptions","organizations_url":"https://api.github.com/users/pengwynn/orgs","repos_url":"https://api.github.com/users/pengwynn/repos","events_url":"https://api.github.com/users/pengwynn/events{/privacy}","received_events_url":"https://api.github.com/users/pengwynn/received_events","type":"User","site_admin":true},"event":"mentioned","commit_id":null,"created_at":"2014-09-15T03:06:52Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/507","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/507/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/507/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/507/events","html_url":"https://github.com/octokit/octokit.rb/pull/507","id":42736570,"number":507,"title":"Implement organization invitation api","user":{"login":"blt04","id":276141,"avatar_url":"https://avatars.githubusercontent.com/u/276141?v=2","gravatar_id":"","url":"https://api.github.com/users/blt04","html_url":"https://github.com/blt04","followers_url":"https://api.github.com/users/blt04/followers","following_url":"https://api.github.com/users/blt04/following{/other_user}","gists_url":"https://api.github.com/users/blt04/gists{/gist_id}","starred_url":"https://api.github.com/users/blt04/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/blt04/subscriptions","organizations_url":"https://api.github.com/users/blt04/orgs","repos_url":"https://api.github.com/users/blt04/repos","events_url":"https://api.github.com/users/blt04/events{/privacy}","received_events_url":"https://api.github.com/users/blt04/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"milestone":null,"comments":3,"created_at":"2014-09-15T01:51:32Z","updated_at":"2014-09-15T13:38:44Z","closed_at":"2014-09-15T13:12:12Z","pull_request":{"url":"https://api.github.com/repos/octokit/octokit.rb/pulls/507","html_url":"https://github.com/octokit/octokit.rb/pull/507","diff_url":"https://github.com/octokit/octokit.rb/pull/507.diff","patch_url":"https://github.com/octokit/octokit.rb/pull/507.patch"},"body":"This is an attempt at API bindings for the new Organization invitation API (https://developer.github.com/changes/2014-08-28-accepting-organization-invitations-from-the-api/).\r\n\r\nI've commented out the tests as I wasn't sure how to record a cassette that could be re-recorded by someone with access to the correct organizations."}},{"id":161802501,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/161802501","actor":{"login":"pengwynn","id":865,"avatar_url":"https://avatars.githubusercontent.com/u/865?v=2","gravatar_id":"","url":"https://api.github.com/users/pengwynn","html_url":"https://github.com/pengwynn","followers_url":"https://api.github.com/users/pengwynn/followers","following_url":"https://api.github.com/users/pengwynn/following{/other_user}","gists_url":"https://api.github.com/users/pengwynn/gists{/gist_id}","starred_url":"https://api.github.com/users/pengwynn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/pengwynn/subscriptions","organizations_url":"https://api.github.com/users/pengwynn/orgs","repos_url":"https://api.github.com/users/pengwynn/repos","events_url":"https://api.github.com/users/pengwynn/events{/privacy}","received_events_url":"https://api.github.com/users/pengwynn/received_events","type":"User","site_admin":true},"event":"closed","commit_id":null,"created_at":"2014-09-05T15:24:22Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/505","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/505/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/505/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/505/events","html_url":"https://github.com/octokit/octokit.rb/pull/505","id":41607580,"number":505,"title":"remove developer preview warning from .combined_status()","user":{"login":"theckman","id":787332,"avatar_url":"https://avatars.githubusercontent.com/u/787332?v=2","gravatar_id":"","url":"https://api.github.com/users/theckman","html_url":"https://github.com/theckman","followers_url":"https://api.github.com/users/theckman/followers","following_url":"https://api.github.com/users/theckman/following{/other_user}","gists_url":"https://api.github.com/users/theckman/gists{/gist_id}","starred_url":"https://api.github.com/users/theckman/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/theckman/subscriptions","organizations_url":"https://api.github.com/users/theckman/orgs","repos_url":"https://api.github.com/users/theckman/repos","events_url":"https://api.github.com/users/theckman/events{/privacy}","received_events_url":"https://api.github.com/users/theckman/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"milestone":null,"comments":1,"created_at":"2014-09-01T05:25:35Z","updated_at":"2014-09-05T15:24:35Z","closed_at":"2014-09-05T15:24:22Z","pull_request":{"url":"https://api.github.com/repos/octokit/octokit.rb/pulls/505","html_url":"https://github.com/octokit/octokit.rb/pull/505","diff_url":"https://github.com/octokit/octokit.rb/pull/505.diff","patch_url":"https://github.com/octokit/octokit.rb/pull/505.patch"},"body":"The combined_status API endpoint is no longer in development preview. This patch makes the following changes:\r\n\r\n* removes the HTTP `Accept` header that was required for this call while it was in its preview period\r\n* remove the warning printed about the method being in the development preview\r\n\r\nAll tests passed locally when following the steps in the contribution information. Please let me know if there are any changes that are needed to be made."}},{"id":161802500,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/161802500","actor":{"login":"pengwynn","id":865,"avatar_url":"https://avatars.githubusercontent.com/u/865?v=2","gravatar_id":"","url":"https://api.github.com/users/pengwynn","html_url":"https://github.com/pengwynn","followers_url":"https://api.github.com/users/pengwynn/followers","following_url":"https://api.github.com/users/pengwynn/following{/other_user}","gists_url":"https://api.github.com/users/pengwynn/gists{/gist_id}","starred_url":"https://api.github.com/users/pengwynn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/pengwynn/subscriptions","organizations_url":"https://api.github.com/users/pengwynn/orgs","repos_url":"https://api.github.com/users/pengwynn/repos","events_url":"https://api.github.com/users/pengwynn/events{/privacy}","received_events_url":"https://api.github.com/users/pengwynn/received_events","type":"User","site_admin":true},"event":"merged","commit_id":"506ade9c3d009d6c466ed85fd8f6b29cb0dc25c3","created_at":"2014-09-05T15:24:22Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/505","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/505/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/505/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/505/events","html_url":"https://github.com/octokit/octokit.rb/pull/505","id":41607580,"number":505,"title":"remove developer preview warning from .combined_status()","user":{"login":"theckman","id":787332,"avatar_url":"https://avatars.githubusercontent.com/u/787332?v=2","gravatar_id":"","url":"https://api.github.com/users/theckman","html_url":"https://github.com/theckman","followers_url":"https://api.github.com/users/theckman/followers","following_url":"https://api.github.com/users/theckman/following{/other_user}","gists_url":"https://api.github.com/users/theckman/gists{/gist_id}","starred_url":"https://api.github.com/users/theckman/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/theckman/subscriptions","organizations_url":"https://api.github.com/users/theckman/orgs","repos_url":"https://api.github.com/users/theckman/repos","events_url":"https://api.github.com/users/theckman/events{/privacy}","received_events_url":"https://api.github.com/users/theckman/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"milestone":null,"comments":1,"created_at":"2014-09-01T05:25:35Z","updated_at":"2014-09-05T15:24:35Z","closed_at":"2014-09-05T15:24:22Z","pull_request":{"url":"https://api.github.com/repos/octokit/octokit.rb/pulls/505","html_url":"https://github.com/octokit/octokit.rb/pull/505","diff_url":"https://github.com/octokit/octokit.rb/pull/505.diff","patch_url":"https://github.com/octokit/octokit.rb/pull/505.patch"},"body":"The combined_status API endpoint is no longer in development preview. This patch makes the following changes:\r\n\r\n* removes the HTTP `Accept` header that was required for this call while it was in its preview period\r\n* remove the warning printed about the method being in the development preview\r\n\r\nAll tests passed locally when following the steps in the contribution information. Please let me know if there are any changes that are needed to be made."}},{"id":161802499,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/161802499","actor":{"login":"pengwynn","id":865,"avatar_url":"https://avatars.githubusercontent.com/u/865?v=2","gravatar_id":"","url":"https://api.github.com/users/pengwynn","html_url":"https://github.com/pengwynn","followers_url":"https://api.github.com/users/pengwynn/followers","following_url":"https://api.github.com/users/pengwynn/following{/other_user}","gists_url":"https://api.github.com/users/pengwynn/gists{/gist_id}","starred_url":"https://api.github.com/users/pengwynn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/pengwynn/subscriptions","organizations_url":"https://api.github.com/users/pengwynn/orgs","repos_url":"https://api.github.com/users/pengwynn/repos","events_url":"https://api.github.com/users/pengwynn/events{/privacy}","received_events_url":"https://api.github.com/users/pengwynn/received_events","type":"User","site_admin":true},"event":"referenced","commit_id":"506ade9c3d009d6c466ed85fd8f6b29cb0dc25c3","created_at":"2014-09-05T15:24:22Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/505","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/505/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/505/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/505/events","html_url":"https://github.com/octokit/octokit.rb/pull/505","id":41607580,"number":505,"title":"remove developer preview warning from .combined_status()","user":{"login":"theckman","id":787332,"avatar_url":"https://avatars.githubusercontent.com/u/787332?v=2","gravatar_id":"","url":"https://api.github.com/users/theckman","html_url":"https://github.com/theckman","followers_url":"https://api.github.com/users/theckman/followers","following_url":"https://api.github.com/users/theckman/following{/other_user}","gists_url":"https://api.github.com/users/theckman/gists{/gist_id}","starred_url":"https://api.github.com/users/theckman/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/theckman/subscriptions","organizations_url":"https://api.github.com/users/theckman/orgs","repos_url":"https://api.github.com/users/theckman/repos","events_url":"https://api.github.com/users/theckman/events{/privacy}","received_events_url":"https://api.github.com/users/theckman/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"milestone":null,"comments":1,"created_at":"2014-09-01T05:25:35Z","updated_at":"2014-09-05T15:24:35Z","closed_at":"2014-09-05T15:24:22Z","pull_request":{"url":"https://api.github.com/repos/octokit/octokit.rb/pulls/505","html_url":"https://github.com/octokit/octokit.rb/pull/505","diff_url":"https://github.com/octokit/octokit.rb/pull/505.diff","patch_url":"https://github.com/octokit/octokit.rb/pull/505.patch"},"body":"The combined_status API endpoint is no longer in development preview. This patch makes the following changes:\r\n\r\n* removes the HTTP `Accept` header that was required for this call while it was in its preview period\r\n* remove the warning printed about the method being in the development preview\r\n\r\nAll tests passed locally when following the steps in the contribution information. Please let me know if there are any changes that are needed to be made."}},{"id":160159423,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/160159423","actor":{"login":"theckman","id":787332,"avatar_url":"https://avatars.githubusercontent.com/u/787332?v=2","gravatar_id":"","url":"https://api.github.com/users/theckman","html_url":"https://github.com/theckman","followers_url":"https://api.github.com/users/theckman/followers","following_url":"https://api.github.com/users/theckman/following{/other_user}","gists_url":"https://api.github.com/users/theckman/gists{/gist_id}","starred_url":"https://api.github.com/users/theckman/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/theckman/subscriptions","organizations_url":"https://api.github.com/users/theckman/orgs","repos_url":"https://api.github.com/users/theckman/repos","events_url":"https://api.github.com/users/theckman/events{/privacy}","received_events_url":"https://api.github.com/users/theckman/received_events","type":"User","site_admin":false},"event":"subscribed","commit_id":null,"created_at":"2014-09-02T18:03:18Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/504","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/504/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/504/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/504/events","html_url":"https://github.com/octokit/octokit.rb/issues/504","id":41553846,"number":504,"title":"rate_limit doesn't always return valid information","user":{"login":"theckman","id":787332,"avatar_url":"https://avatars.githubusercontent.com/u/787332?v=2","gravatar_id":"","url":"https://api.github.com/users/theckman","html_url":"https://github.com/theckman","followers_url":"https://api.github.com/users/theckman/followers","following_url":"https://api.github.com/users/theckman/following{/other_user}","gists_url":"https://api.github.com/users/theckman/gists{/gist_id}","starred_url":"https://api.github.com/users/theckman/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/theckman/subscriptions","organizations_url":"https://api.github.com/users/theckman/orgs","repos_url":"https://api.github.com/users/theckman/repos","events_url":"https://api.github.com/users/theckman/events{/privacy}","received_events_url":"https://api.github.com/users/theckman/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"milestone":null,"comments":3,"created_at":"2014-08-30T03:02:38Z","updated_at":"2014-09-02T18:03:18Z","closed_at":null,"body":"If you use Octokit in a long running piece of software with infrequent API calls, the `rate_limit` Client method can return stale/invalid date.\r\n\r\nI've taken a quick glance at the code and it looks like the rate limit information is pulled from the headers of the last request. After some time the information itself becomes stale, and eventually the `resets_in` field in the Struct becomes a negative number. This happens because time has progressed past the `resets_at` time, yet the information hasn't been refreshed.\r\n\r\nIs there a reason why the `/rate_limit` API endpoint isn't used?"}},{"id":160159422,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/160159422","actor":{"login":"theckman","id":787332,"avatar_url":"https://avatars.githubusercontent.com/u/787332?v=2","gravatar_id":"","url":"https://api.github.com/users/theckman","html_url":"https://github.com/theckman","followers_url":"https://api.github.com/users/theckman/followers","following_url":"https://api.github.com/users/theckman/following{/other_user}","gists_url":"https://api.github.com/users/theckman/gists{/gist_id}","starred_url":"https://api.github.com/users/theckman/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/theckman/subscriptions","organizations_url":"https://api.github.com/users/theckman/orgs","repos_url":"https://api.github.com/users/theckman/repos","events_url":"https://api.github.com/users/theckman/events{/privacy}","received_events_url":"https://api.github.com/users/theckman/received_events","type":"User","site_admin":false},"event":"mentioned","commit_id":null,"created_at":"2014-09-02T18:03:18Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/504","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/504/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/504/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/504/events","html_url":"https://github.com/octokit/octokit.rb/issues/504","id":41553846,"number":504,"title":"rate_limit doesn't always return valid information","user":{"login":"theckman","id":787332,"avatar_url":"https://avatars.githubusercontent.com/u/787332?v=2","gravatar_id":"","url":"https://api.github.com/users/theckman","html_url":"https://github.com/theckman","followers_url":"https://api.github.com/users/theckman/followers","following_url":"https://api.github.com/users/theckman/following{/other_user}","gists_url":"https://api.github.com/users/theckman/gists{/gist_id}","starred_url":"https://api.github.com/users/theckman/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/theckman/subscriptions","organizations_url":"https://api.github.com/users/theckman/orgs","repos_url":"https://api.github.com/users/theckman/repos","events_url":"https://api.github.com/users/theckman/events{/privacy}","received_events_url":"https://api.github.com/users/theckman/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"milestone":null,"comments":3,"created_at":"2014-08-30T03:02:38Z","updated_at":"2014-09-02T18:03:18Z","closed_at":null,"body":"If you use Octokit in a long running piece of software with infrequent API calls, the `rate_limit` Client method can return stale/invalid date.\r\n\r\nI've taken a quick glance at the code and it looks like the rate limit information is pulled from the headers of the last request. After some time the information itself becomes stale, and eventually the `resets_in` field in the Struct becomes a negative number. This happens because time has progressed past the `resets_at` time, yet the information hasn't been refreshed.\r\n\r\nIs there a reason why the `/rate_limit` API endpoint isn't used?"}},{"id":156186364,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/156186364","actor":{"login":"codemanmeet","id":4116346,"avatar_url":"https://avatars.githubusercontent.com/u/4116346?v=2","gravatar_id":"","url":"https://api.github.com/users/codemanmeet","html_url":"https://github.com/codemanmeet","followers_url":"https://api.github.com/users/codemanmeet/followers","following_url":"https://api.github.com/users/codemanmeet/following{/other_user}","gists_url":"https://api.github.com/users/codemanmeet/gists{/gist_id}","starred_url":"https://api.github.com/users/codemanmeet/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/codemanmeet/subscriptions","organizations_url":"https://api.github.com/users/codemanmeet/orgs","repos_url":"https://api.github.com/users/codemanmeet/repos","events_url":"https://api.github.com/users/codemanmeet/events{/privacy}","received_events_url":"https://api.github.com/users/codemanmeet/received_events","type":"User","site_admin":false},"event":"closed","commit_id":null,"created_at":"2014-08-22T17:39:00Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/503","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/503/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/503/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/503/events","html_url":"https://github.com/octokit/octokit.rb/issues/503","id":40930945,"number":503,"title":"Direction parameter not working for sorting issues","user":{"login":"codemanmeet","id":4116346,"avatar_url":"https://avatars.githubusercontent.com/u/4116346?v=2","gravatar_id":"","url":"https://api.github.com/users/codemanmeet","html_url":"https://github.com/codemanmeet","followers_url":"https://api.github.com/users/codemanmeet/followers","following_url":"https://api.github.com/users/codemanmeet/following{/other_user}","gists_url":"https://api.github.com/users/codemanmeet/gists{/gist_id}","starred_url":"https://api.github.com/users/codemanmeet/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/codemanmeet/subscriptions","organizations_url":"https://api.github.com/users/codemanmeet/orgs","repos_url":"https://api.github.com/users/codemanmeet/repos","events_url":"https://api.github.com/users/codemanmeet/events{/privacy}","received_events_url":"https://api.github.com/users/codemanmeet/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"milestone":null,"comments":1,"created_at":"2014-08-22T17:32:48Z","updated_at":"2014-08-22T17:41:00Z","closed_at":"2014-08-22T17:39:00Z","body":"I gave a shot at sorting issues using the Github API for [Issues][1] but the 'direction' parameter doesn't seem to work. The sort is happening to open assigned issues by the 'created' time. I tried using curl and even the API but the direction=asc and direction=desc both give the same direction for the results. This is the curl command I used - \r\n\r\n``curl -i -H 'Authorization: token OAUTH Token' https://api.github.com/issues?direction=asc``\r\n\r\n[1]: https://developer.github.com/v3/issues/"}},{"id":155317784,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/155317784","actor":{"login":"pengwynn","id":865,"avatar_url":"https://avatars.githubusercontent.com/u/865?v=2","gravatar_id":"","url":"https://api.github.com/users/pengwynn","html_url":"https://github.com/pengwynn","followers_url":"https://api.github.com/users/pengwynn/followers","following_url":"https://api.github.com/users/pengwynn/following{/other_user}","gists_url":"https://api.github.com/users/pengwynn/gists{/gist_id}","starred_url":"https://api.github.com/users/pengwynn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/pengwynn/subscriptions","organizations_url":"https://api.github.com/users/pengwynn/orgs","repos_url":"https://api.github.com/users/pengwynn/repos","events_url":"https://api.github.com/users/pengwynn/events{/privacy}","received_events_url":"https://api.github.com/users/pengwynn/received_events","type":"User","site_admin":true},"event":"closed","commit_id":null,"created_at":"2014-08-20T23:55:34Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/502","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/502/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/502/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/502/events","html_url":"https://github.com/octokit/octokit.rb/pull/502","id":40757826,"number":502,"title":"Fix Readme so the upgrade notice is more generic.","user":{"login":"wdperson","id":601,"avatar_url":"https://avatars.githubusercontent.com/u/601?v=2","gravatar_id":"","url":"https://api.github.com/users/wdperson","html_url":"https://github.com/wdperson","followers_url":"https://api.github.com/users/wdperson/followers","following_url":"https://api.github.com/users/wdperson/following{/other_user}","gists_url":"https://api.github.com/users/wdperson/gists{/gist_id}","starred_url":"https://api.github.com/users/wdperson/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/wdperson/subscriptions","organizations_url":"https://api.github.com/users/wdperson/orgs","repos_url":"https://api.github.com/users/wdperson/repos","events_url":"https://api.github.com/users/wdperson/events{/privacy}","received_events_url":"https://api.github.com/users/wdperson/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"milestone":null,"comments":1,"created_at":"2014-08-20T23:46:46Z","updated_at":"2014-08-20T23:55:34Z","closed_at":"2014-08-20T23:55:34Z","pull_request":{"url":"https://api.github.com/repos/octokit/octokit.rb/pulls/502","html_url":"https://github.com/octokit/octokit.rb/pull/502","diff_url":"https://github.com/octokit/octokit.rb/pull/502.diff","patch_url":"https://github.com/octokit/octokit.rb/pull/502.patch"},"body":"I created this pull request so that the upgrade warning is a bit more generic so it doesn't have to be updated with every new version of Octokit.  It now reads that Octokit 2.0 is out while in fact, I just got 3.3.1.  Hope this helps."}},{"id":155317783,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/155317783","actor":{"login":"pengwynn","id":865,"avatar_url":"https://avatars.githubusercontent.com/u/865?v=2","gravatar_id":"","url":"https://api.github.com/users/pengwynn","html_url":"https://github.com/pengwynn","followers_url":"https://api.github.com/users/pengwynn/followers","following_url":"https://api.github.com/users/pengwynn/following{/other_user}","gists_url":"https://api.github.com/users/pengwynn/gists{/gist_id}","starred_url":"https://api.github.com/users/pengwynn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/pengwynn/subscriptions","organizations_url":"https://api.github.com/users/pengwynn/orgs","repos_url":"https://api.github.com/users/pengwynn/repos","events_url":"https://api.github.com/users/pengwynn/events{/privacy}","received_events_url":"https://api.github.com/users/pengwynn/received_events","type":"User","site_admin":true},"event":"merged","commit_id":"ef13851956464998d59e6c02a721b93267a13e1e","created_at":"2014-08-20T23:55:34Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/502","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/502/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/502/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/502/events","html_url":"https://github.com/octokit/octokit.rb/pull/502","id":40757826,"number":502,"title":"Fix Readme so the upgrade notice is more generic.","user":{"login":"wdperson","id":601,"avatar_url":"https://avatars.githubusercontent.com/u/601?v=2","gravatar_id":"","url":"https://api.github.com/users/wdperson","html_url":"https://github.com/wdperson","followers_url":"https://api.github.com/users/wdperson/followers","following_url":"https://api.github.com/users/wdperson/following{/other_user}","gists_url":"https://api.github.com/users/wdperson/gists{/gist_id}","starred_url":"https://api.github.com/users/wdperson/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/wdperson/subscriptions","organizations_url":"https://api.github.com/users/wdperson/orgs","repos_url":"https://api.github.com/users/wdperson/repos","events_url":"https://api.github.com/users/wdperson/events{/privacy}","received_events_url":"https://api.github.com/users/wdperson/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"milestone":null,"comments":1,"created_at":"2014-08-20T23:46:46Z","updated_at":"2014-08-20T23:55:34Z","closed_at":"2014-08-20T23:55:34Z","pull_request":{"url":"https://api.github.com/repos/octokit/octokit.rb/pulls/502","html_url":"https://github.com/octokit/octokit.rb/pull/502","diff_url":"https://github.com/octokit/octokit.rb/pull/502.diff","patch_url":"https://github.com/octokit/octokit.rb/pull/502.patch"},"body":"I created this pull request so that the upgrade warning is a bit more generic so it doesn't have to be updated with every new version of Octokit.  It now reads that Octokit 2.0 is out while in fact, I just got 3.3.1.  Hope this helps."}},{"id":155317782,"url":"https://api.github.com/repos/octokit/octokit.rb/issues/events/155317782","actor":{"login":"pengwynn","id":865,"avatar_url":"https://avatars.githubusercontent.com/u/865?v=2","gravatar_id":"","url":"https://api.github.com/users/pengwynn","html_url":"https://github.com/pengwynn","followers_url":"https://api.github.com/users/pengwynn/followers","following_url":"https://api.github.com/users/pengwynn/following{/other_user}","gists_url":"https://api.github.com/users/pengwynn/gists{/gist_id}","starred_url":"https://api.github.com/users/pengwynn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/pengwynn/subscriptions","organizations_url":"https://api.github.com/users/pengwynn/orgs","repos_url":"https://api.github.com/users/pengwynn/repos","events_url":"https://api.github.com/users/pengwynn/events{/privacy}","received_events_url":"https://api.github.com/users/pengwynn/received_events","type":"User","site_admin":true},"event":"referenced","commit_id":"ef13851956464998d59e6c02a721b93267a13e1e","created_at":"2014-08-20T23:55:34Z","issue":{"url":"https://api.github.com/repos/octokit/octokit.rb/issues/502","labels_url":"https://api.github.com/repos/octokit/octokit.rb/issues/502/labels{/name}","comments_url":"https://api.github.com/repos/octokit/octokit.rb/issues/502/comments","events_url":"https://api.github.com/repos/octokit/octokit.rb/issues/502/events","html_url":"https://github.com/octokit/octokit.rb/pull/502","id":40757826,"number":502,"title":"Fix Readme so the upgrade notice is more generic.","user":{"login":"wdperson","id":601,"avatar_url":"https://avatars.githubusercontent.com/u/601?v=2","gravatar_id":"","url":"https://api.github.com/users/wdperson","html_url":"https://github.com/wdperson","followers_url":"https://api.github.com/users/wdperson/followers","following_url":"https://api.github.com/users/wdperson/following{/other_user}","gists_url":"https://api.github.com/users/wdperson/gists{/gist_id}","starred_url":"https://api.github.com/users/wdperson/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/wdperson/subscriptions","organizations_url":"https://api.github.com/users/wdperson/orgs","repos_url":"https://api.github.com/users/wdperson/repos","events_url":"https://api.github.com/users/wdperson/events{/privacy}","received_events_url":"https://api.github.com/users/wdperson/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"milestone":null,"comments":1,"created_at":"2014-08-20T23:46:46Z","updated_at":"2014-08-20T23:55:34Z","closed_at":"2014-08-20T23:55:34Z","pull_request":{"url":"https://api.github.com/repos/octokit/octokit.rb/pulls/502","html_url":"https://github.com/octokit/octokit.rb/pull/502","diff_url":"https://github.com/octokit/octokit.rb/pull/502.diff","patch_url":"https://github.com/octokit/octokit.rb/pull/502.patch"},"body":"I created this pull request so that the upgrade warning is a bit more generic so it doesn't have to be updated with every new version of Octokit.  It now reads that Octokit 2.0 is out while in fact, I just got 3.3.1.  Hope this helps."}}]